# -*- coding: utf-8 -*-
"""5-FOLD CV + McNEMAR'S AND BOOTSTRAP ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mX9QcHyv9HeZSmv3Psfq8efhIBMoZzfL
"""



# =============================================================================
#  5-FOLD CV + McNEMAR'S TEST (Complete, Production-Ready)
# =============================================================================
#
#
# =============================================================================

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import f1_score, accuracy_score, classification_report
from scipy.stats import chi2, wilcoxon
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import warnings, os, time
warnings.filterwarnings('ignore')

device     = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
output_dir = './ecg_results_figures'
os.makedirs(output_dir, exist_ok=True)

CLASS_NAMES = ['Normal (N)', 'Supra (S)', 'PVC (V)', 'Fusion (F)', 'Unknown (Q)']

# =============================================================================
# ARCHITECTURES
# =============================================================================

class _SEBlock(nn.Module):
    def __init__(self, ch, r=16):
        super().__init__()
        self.pool = nn.AdaptiveAvgPool1d(1)
        self.fc   = nn.Sequential(
            nn.Linear(ch, max(ch // r, 4), bias=False), nn.ReLU(True),
            nn.Linear(max(ch // r, 4), ch, bias=False), nn.Sigmoid())
    def forward(self, x):
        b, c, _ = x.shape
        return x * self.fc(self.pool(x).view(b, c)).view(b, c, 1)

class _ResBlock(nn.Module):
    def __init__(self, ic, oc, stride=1):
        super().__init__()
        self.c1   = nn.Conv1d(ic, oc, 3, stride=stride, padding=1, bias=False)
        self.bn1  = nn.BatchNorm1d(oc)
        self.c2   = nn.Conv1d(oc, oc, 3, padding=1, bias=False)
        self.bn2  = nn.BatchNorm1d(oc)
        self.se   = _SEBlock(oc)
        self.skip = (nn.Sequential(nn.Conv1d(ic, oc, 1, stride=stride, bias=False),
                                    nn.BatchNorm1d(oc))
                     if ic != oc or stride != 1 else nn.Identity())
    def forward(self, x):
        out = F.relu(self.bn1(self.c1(x)))
        out = self.se(self.bn2(self.c2(out)))
        return F.relu(out + self.skip(x))

class ECGResNetSE_stat(nn.Module):
    """Baseline: ECGResNetSE for statistical comparison."""
    def __init__(self, num_classes=5, dropout=0.4):
        super().__init__()
        self.stem = nn.Sequential(
            nn.Conv1d(1, 32, 7, stride=2, padding=3, bias=False),
            nn.BatchNorm1d(32), nn.ReLU(True),
            nn.Conv1d(32, 32, 3, padding=1, bias=False),
            nn.BatchNorm1d(32), nn.ReLU(True))
        self.l1   = _ResBlock(32, 64, stride=2)
        self.l2   = _ResBlock(64, 128, stride=2)
        self.l3   = _ResBlock(128, 128)
        self.pool = nn.AdaptiveAvgPool1d(1)
        self.drop = nn.Dropout(dropout)
        self.fc   = nn.Linear(128, num_classes)
    def forward(self, x):
        if x.dim() == 2: x = x.unsqueeze(1)
        return self.fc(self.drop(self.pool(
            self.l3(self.l2(self.l1(self.stem(x))))).squeeze(-1)))

class MultiScaleECGCNN_stat(nn.Module):
    """MultiScale CNN for CV (local clone if Cell 17 not in scope)."""
    def __init__(self, num_classes=5, dropout=0.5):
        super().__init__()
        ch = 48
        def _p(k):
            return nn.Sequential(
                nn.Conv1d(1, ch, k, padding=k//2, bias=False), nn.BatchNorm1d(ch), nn.ReLU(True),
                nn.Dropout(dropout * 0.5),
                nn.Conv1d(ch, ch, k, padding=k//2, bias=False), nn.BatchNorm1d(ch), nn.ReLU(True),
                nn.AdaptiveAvgPool1d(32))
        self.p1, self.p2, self.p3 = _p(3), _p(9), _p(21)
        mc = ch * 3
        self.se      = _SEBlock(mc, r=8)
        self.fusion  = nn.Sequential(
            nn.Dropout(dropout * 0.6),
            nn.Conv1d(mc, 96, 3, padding=1, bias=False), nn.BatchNorm1d(96), nn.ReLU(True),
            nn.AdaptiveAvgPool1d(1))
        self.clf     = nn.Sequential(
            nn.Dropout(dropout), nn.Linear(96, 64), nn.ReLU(True),
            nn.Dropout(dropout * 0.5), nn.Linear(64, num_classes))
    def forward(self, x):
        if x.dim() == 2: x = x.unsqueeze(1)
        f = torch.cat([self.p1(x), self.p2(x), self.p3(x)], 1)
        return self.clf(self.fusion(self.se(f)).squeeze(-1))

# Try to use the fully trained Cell-17 model class for CV
try:
    _ = MultiScaleECGCNN_v2(num_classes=5)
    MS_CLS = MultiScaleECGCNN_v2
    print('[OK] Using MultiScaleECGCNN_v2 from Cell 17 for CV')
except NameError:
    MS_CLS = MultiScaleECGCNN_stat
    print('[INFO] Using local MultiScaleECGCNN_stat clone')

# =============================================================================
# DATA
# =============================================================================

# Training pool: X_train + X_val (for CV)
try:
    X_cv   = np.concatenate([X_train, X_val], axis=0).astype(np.float32)
    y_cv   = np.concatenate([y_train, y_val], axis=0)
    DATA_SRC = 'REAL'
    print(f'[OK] CV pool: {X_cv.shape}  classes: {dict(zip(*np.unique(y_cv, return_counts=True)))}')
except NameError:
    np.random.seed(0); t = np.linspace(0, 1, 187); Xl, yl = [], []
    for c in range(5):
        for _ in range(1000):
            s = np.exp(-((t-.45)**2)/(2*.01**2)) + np.random.normal(0,.05,187)
            if c == 1: s += .3*np.sin(2*np.pi*5*t)
            if c == 2: s[80:110] *= .4
            Xl.append(s.astype(np.float32)); yl.append(c)
    X_cv = np.array(Xl); y_cv = np.array(yl)
    DATA_SRC = 'SYNTHETIC'

# True held-out test set: mitbih_test.csv (loaded by Cell 7B)
try:
    X_heldout = X_test_kaggle.astype(np.float32)
    y_heldout = y_test_kaggle
    print(f'[OK] Held-out test (mitbih_test.csv): {X_heldout.shape}')
    TEST_SRC = 'mitbih_test.csv'
except NameError:
    # Fallback: use last 20% of CV pool
    from sklearn.model_selection import train_test_split as _tts
    X_cv, X_heldout, y_cv, y_heldout = _tts(
        X_cv, y_cv, test_size=0.2, stratify=y_cv, random_state=42)
    TEST_SRC = 'X_val fallback (run Cell 7B for true held-out test)'
    print(f'[WARN] mitbih_test.csv not loaded — fallback to split. Test: {X_heldout.shape}')

# =============================================================================
# TRAINING HELPER
# =============================================================================

EPOCHS_CV = 20
BATCH_CV  = 256

def _train_eval(ModelCls, X_tr, y_tr, X_vl, y_vl):
    m    = ModelCls(num_classes=5).to(device)
    opt  = torch.optim.AdamW(m.parameters(), lr=5e-4, weight_decay=1e-3)
    crit = nn.CrossEntropyLoss(label_smoothing=0.1)
    def _lr(ep): return (ep+1)/2 if ep < 2 else 0.5*(1+np.cos(np.pi*(ep-2)/(EPOCHS_CV-2)))
    sch  = torch.optim.lr_scheduler.LambdaLR(opt, _lr)
    ld   = DataLoader(TensorDataset(
               torch.tensor(X_tr, dtype=torch.float32),
               torch.tensor(y_tr, dtype=torch.long)),
               batch_size=BATCH_CV, shuffle=True, drop_last=True)
    for ep in range(EPOCHS_CV):
        m.train()
        for xb, yb in ld:
            xb, yb = xb.to(device), yb.to(device)
            opt.zero_grad(); crit(m(xb), yb).backward(); opt.step()
        sch.step()
    m.eval()
    vl_ld = DataLoader(TensorDataset(
                torch.tensor(X_vl, dtype=torch.float32),
                torch.tensor(y_vl, dtype=torch.long)),
                batch_size=512, shuffle=False)
    preds, trues = [], []
    with torch.no_grad():
        for xb, yb in vl_ld:
            preds.extend(m(xb.to(device)).argmax(1).cpu().numpy())
            trues.extend(yb.numpy())
    return f1_score(trues, preds, average='macro'), np.array(preds), m

def _get_preds(m, X):
    m.eval()
    preds = []
    with torch.no_grad():
        for s in range(0, len(X), 512):
            xb = torch.tensor(X[s:s+512], dtype=torch.float32).to(device)
            preds.extend(m(xb).argmax(1).cpu().numpy())
    return np.array(preds)

# =============================================================================
# PART 1 — 5-FOLD STRATIFIED CROSS-VALIDATION
# =============================================================================

print('\n' + '='*62)
print(f'  5-FOLD STRATIFIED CROSS-VALIDATION  [{DATA_SRC} data]')
print(f'  Both models: {EPOCHS_CV} epochs | batch={BATCH_CV} | warmup+cosine LR')
print(f'  SMOTE applied PER-FOLD on training split only (no leakage)')
print('='*62)

skf    = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_ms  = []   # MultiScaleECGCNN fold F1s
cv_rn  = []   # ECGResNetSE fold F1s
t0_cv  = time.time()

# ── RESUME SUPPORT: load completed-fold progress from Drive if it exists ─────
import os, json as _json
try:
    _CKPT_DIR_CV = CKPT_DIR
except NameError:
    _CKPT_DIR_CV = "./checkpoints"
os.makedirs(_CKPT_DIR_CV, exist_ok=True)
CV_STATE = os.path.join(_CKPT_DIR_CV, "cv_progress.json")

start_fold = 0
if os.path.exists(CV_STATE):
    with open(CV_STATE) as _f:
        _cv_prog = _json.load(_f)
    cv_ms      = _cv_prog["cv_ms"]
    cv_rn      = _cv_prog["cv_rn"]
    start_fold = _cv_prog["completed_folds"]
    if start_fold > 0:
        print(f"[RESUME] Found {start_fold}/5 completed folds — continuing from fold {start_fold+1}")
        for _i in range(start_fold):
            print(f"  Fold {_i+1}/5  MultiScale={cv_ms[_i]:.4f}  ResNetSE={cv_rn[_i]:.4f}  (loaded)")
else:
    print("[INFO] No CV progress found — starting fresh from fold 1")

_all_folds = list(enumerate(skf.split(X_cv, y_cv)))

for fold, (tr_idx, val_idx) in _all_folds[start_fold:]:
    Xtr_raw, ytr_raw = X_cv[tr_idx], y_cv[tr_idx]
    Xvl, yvl         = X_cv[val_idx], y_cv[val_idx]

    # Apply SMOTE INSIDE the fold on training split only (prevents leakage)
    try:
        from imblearn.over_sampling import SMOTE as _SMOTE
        _sm   = _SMOTE(k_neighbors=SMOTE_K_NEIGHBORS if 'SMOTE_K_NEIGHBORS' in dir() else 5,
                       random_state=42 + fold)
        Xtr, ytr = _sm.fit_resample(Xtr_raw, ytr_raw)
        Xtr = Xtr.astype(np.float32)
    except Exception as _se:
        Xtr, ytr = Xtr_raw, ytr_raw   # fallback: no SMOTE
        if fold == 0:
            print(f'  [WARN] SMOTE skipped: {_se}')

    f1_ms, _, _ = _train_eval(MS_CLS,          Xtr, ytr, Xvl, yvl)
    f1_rn, _, _ = _train_eval(ECGResNetSE_stat, Xtr, ytr, Xvl, yvl)

    cv_ms.append(f1_ms); cv_rn.append(f1_rn)
    diff = f1_ms - f1_rn
    print(f'  Fold {fold+1}/5  MultiScale={f1_ms:.4f}  ResNetSE={f1_rn:.4f}  '
          f'diff={diff:+.4f}')

    # Save progress after EACH fold — a disconnect now loses at most one fold
    with open(CV_STATE, "w") as _f:
        _json.dump({"cv_ms": cv_ms, "cv_rn": cv_rn,
                    "completed_folds": fold + 1}, _f)

cv_ms = np.array(cv_ms); cv_rn = np.array(cv_rn)

def _ci95(arr):
    m = arr.mean()
    se = arr.std() / np.sqrt(len(arr))
    return m - 1.96*se, m + 1.96*se

ci_ms = _ci95(cv_ms); ci_rn = _ci95(cv_rn)

# Paired Wilcoxon signed-rank test across folds
if len(cv_ms) >= 5:
    try:
        wstat, wp = wilcoxon(cv_ms, cv_rn)
        wtest_str = f'Wilcoxon W={wstat:.1f}  p={wp:.4f}  '
        wtest_str += ('SIGNIFICANT (p<0.05)' if wp < 0.05 else 'not significant')
    except Exception:
        wtest_str = 'Wilcoxon: insufficient variation'
else:
    wtest_str = 'Wilcoxon: need >= 5 folds'

print(f'\n  ┌──────────────────────────────────────────────────────────┐')
print(f'  │  MultiScaleECGCNN  {cv_ms.mean():.4f} ± {cv_ms.std():.4f}  '
      f'95% CI [{ci_ms[0]:.4f},{ci_ms[1]:.4f}]  │')
print(f'  │  ECGResNetSE       {cv_rn.mean():.4f} ± {cv_rn.std():.4f}  '
      f'95% CI [{ci_rn[0]:.4f},{ci_rn[1]:.4f}]  │')
print(f'  │  {wtest_str:<56}  │')
print(f'  └──────────────────────────────────────────────────────────┘')
print(f'  Total CV time: {time.time()-t0_cv:.0f}s')

# =============================================================================
# PART 2 — McNEMAR'S TEST ON TRUE HELD-OUT TEST SET
# =============================================================================

print('\n' + '='*62)
print(f'  McNEMAR\'S TEST  [{TEST_SRC}  n={len(y_heldout):,}]')
print(f'  MultiScaleECGCNN (Cell-17 weights) vs ECGResNetSE (trained here)')
print('='*62)

# Get MultiScaleECGCNN predictions: prefer Cell-17 fully-trained model
try:
    ms_model = model
    ms_model.eval().to(device)
    preds_ms = _get_preds(ms_model, X_heldout)
    print('[OK] Using Cell-17 MultiScaleECGCNN (full training)')
except NameError:
    print('[INFO] Cell-17 model not found — training MultiScaleECGCNN on full CV pool')
    _, _, ms_model = _train_eval(MS_CLS, X_cv, y_cv, X_heldout, y_heldout)
    preds_ms = _get_preds(ms_model, X_heldout)

# Train ECGResNetSE on full CV pool
print('[INFO] Training ECGResNetSE on full CV pool for McNemar comparison...')
_, _, rn_model = _train_eval(ECGResNetSE_stat, X_cv, y_cv, X_heldout, y_heldout)
preds_rn = _get_preds(rn_model, X_heldout)

f1_ms_t = f1_score(y_heldout, preds_ms, average='macro')
f1_rn_t = f1_score(y_heldout, preds_rn, average='macro')
acc_ms_t = accuracy_score(y_heldout, preds_ms)
acc_rn_t = accuracy_score(y_heldout, preds_rn)

print(f'\n  Test-set performance ({TEST_SRC}):')
print(f'  MultiScaleECGCNN  Macro F1={f1_ms_t:.4f}  Acc={acc_ms_t:.4f}')
print(f'  ECGResNetSE       Macro F1={f1_rn_t:.4f}  Acc={acc_rn_t:.4f}')

# Overall McNemar contingency table
ms_c   = (preds_ms == y_heldout)
rn_c   = (preds_rn == y_heldout)
b      = int(np.sum( ms_c & ~rn_c))   # MS correct, RN wrong
c_cell = int(np.sum(~ms_c &  rn_c))   # MS wrong, RN correct
both_c = int(np.sum( ms_c &  rn_c))
both_w = int(np.sum(~ms_c & ~rn_c))

# McNemar with continuity correction
chi2_stat = (abs(b - c_cell) - 1)**2 / (b + c_cell + 1e-8)
p_val     = 1 - chi2.cdf(chi2_stat, df=1)
sig_str   = ('SIGNIFICANT (p<0.001)' if p_val < 0.001 else
             'SIGNIFICANT (p<0.05)'  if p_val < 0.05  else 'not significant')

print(f'\n  OVERALL McNEMAR CONTINGENCY:')
print(f'                        ResNetSE correct  ResNetSE wrong')
print(f'  MultiScale correct  |  {both_c:>8,}       {b:>8,}')
print(f'  MultiScale wrong    |  {c_cell:>8,}       {both_w:>8,}')
print(f'  chi2={chi2_stat:.2f}  p={p_val:.2e}  → {sig_str}')

# Per-class McNemar breakdown
print(f'\n  PER-CLASS McNEMAR BREAKDOWN:')
print(f'  {"Class":<16} {"MS_F1":>6}  {"RN_F1":>6}  {"b":>6}  {"c":>6}  {"chi2":>7}  {"p":>8}  Verdict')
print('  ' + '-'*80)
per_class_results = []
for cls in range(5):
    mask   = (y_heldout == cls)
    if mask.sum() == 0:
        print(f'  {CLASS_NAMES[cls]:<16}: no samples')
        continue
    # FIXED: one-vs-rest binarisation over the FULL held-out set (not just
    # the masked subset) so f1_score sees true binary 0/1 arrays. Computing
    # binary F1 on the cls-only mask is also semantically wrong for recall,
    # since the negative class is excluded entirely by the mask.
    y_bin      = (y_heldout == cls).astype(int)
    preds_ms_bin = (preds_ms == cls).astype(int)
    preds_rn_bin = (preds_rn == cls).astype(int)
    f1_ms_c = f1_score(y_bin, preds_ms_bin, average='binary',
                       pos_label=1, zero_division=0)
    f1_rn_c = f1_score(y_bin, preds_rn_bin, average='binary',
                       pos_label=1, zero_division=0)
    # One-vs-rest McNemar for this class
    ms_cc  = (preds_ms[mask] == cls)
    rn_cc  = (preds_rn[mask] == cls)
    bc     = int(np.sum( ms_cc & ~rn_cc))
    cc     = int(np.sum(~ms_cc &  rn_cc))
    if bc + cc > 0:
        chi2_c = (abs(bc - cc) - 1)**2 / (bc + cc + 1e-8)
        p_c    = 1 - chi2.cdf(chi2_c, df=1)
    else:
        chi2_c, p_c = 0.0, 1.0
    verd_c = 'SIG*' if p_c < 0.05 else 'ns'
    print(f'  {CLASS_NAMES[cls]:<16} {f1_ms_c:6.4f}  {f1_rn_c:6.4f}  '
          f'{bc:6d}  {cc:6d}  {chi2_c:7.2f}  {p_c:8.4f}  {verd_c}')
    per_class_results.append((CLASS_NAMES[cls], f1_ms_c, f1_rn_c, chi2_c, p_c))

# Bootstrap 95% CI on macro F1
rng_b = np.random.default_rng(42)
bms_f, brn_f = [], []
for _ in range(1000):
    idx = rng_b.integers(0, len(y_heldout), size=len(y_heldout))
    bms_f.append(f1_score(y_heldout[idx], preds_ms[idx], average='macro', zero_division=0))
    brn_f.append(f1_score(y_heldout[idx], preds_rn[idx], average='macro', zero_division=0))
bms_f = np.array(bms_f); brn_f = np.array(brn_f)
ci_ms_b = np.percentile(bms_f, [2.5, 97.5])
ci_rn_b = np.percentile(brn_f, [2.5, 97.5])
print(f'\n  BOOTSTRAP 95% CI (n=1000 iterations):')
print(f'  MultiScaleECGCNN  {bms_f.mean():.4f}  [{ci_ms_b[0]:.4f}, {ci_ms_b[1]:.4f}]')
print(f'  ECGResNetSE       {brn_f.mean():.4f}  [{ci_rn_b[0]:.4f}, {ci_rn_b[1]:.4f}]')

# =============================================================================
# FIGURE — 4 panels: CV bars | fold F1 line | McNemar table | per-class McNemar
# =============================================================================

BG   = '#0d1117'; PAN  = '#161b22'; TX   = '#c9d1d9'; TX2  = '#8b949e'
GRID = '#30363d'; GREEN = '#2ea44f'; RED  = '#e5534b'
BLUE = '#58a6ff'; GOLD  = '#d29922'; PURP = '#bc8cff'
MS_COL = BLUE; RN_COL = GOLD

fig, axes = plt.subplots(2, 2, figsize=(20, 14), facecolor=BG)
fig.suptitle(
    '5-Fold Cross-Validation + McNemar\'s Test\n'
    f'MultiScaleECGCNN vs ECGResNetSE  |  Data: {DATA_SRC}  |  Test: {TEST_SRC}',
    color=TX, fontsize=13, fontweight='bold')
for ax in axes.flat:
    ax.set_facecolor(PAN)
    for sp in ax.spines.values(): sp.set_color(GRID)
    ax.tick_params(colors=TX2)
    ax.grid(color=GRID, lw=0.4, alpha=0.5)

# Panel A — CV bars per fold
x = np.arange(5); w = 0.35
axes[0,0].bar(x - w/2, cv_ms, w, color=MS_COL, alpha=0.85, label='MultiScaleECGCNN', zorder=3)
axes[0,0].bar(x + w/2, cv_rn, w, color=RN_COL, alpha=0.85, label='ECGResNetSE',      zorder=3)
for xi, (ms, rn) in enumerate(zip(cv_ms, cv_rn)):
    axes[0,0].text(xi-w/2, ms+0.005, f'{ms:.3f}', ha='center', color=TX, fontsize=8)
    axes[0,0].text(xi+w/2, rn+0.005, f'{rn:.3f}', ha='center', color=TX, fontsize=8)
axes[0,0].axhline(cv_ms.mean(), color=MS_COL, ls='--', lw=1.5, label=f'MS mean={cv_ms.mean():.4f}')
axes[0,0].axhline(cv_rn.mean(), color=RN_COL, ls='--', lw=1.5, label=f'RN mean={cv_rn.mean():.4f}')
axes[0,0].set_xticks(x)
axes[0,0].set_xticklabels([f'Fold {i+1}' for i in range(5)], color=TX2)
axes[0,0].set_ylabel('Macro F1', color=TX2)
axes[0,0].set_ylim(max(0, min(cv_ms.min(), cv_rn.min()) - 0.05), 1.0)
axes[0,0].set_title(
    f'5-Fold CV  |  MultiScale {cv_ms.mean():.4f}±{cv_ms.std():.4f}  '
    f'ResNetSE {cv_rn.mean():.4f}±{cv_rn.std():.4f}\n{wtest_str}',
    color=TX, fontsize=10, fontweight='bold')
axes[0,0].legend(facecolor=PAN, labelcolor=TX, fontsize=9)

# Panel B — per-fold F1 line plot with diff shading
fold_x = np.arange(1, 6)
axes[0,1].plot(fold_x, cv_ms, 'o-', color=MS_COL, lw=2, ms=7, label='MultiScaleECGCNN')
axes[0,1].plot(fold_x, cv_rn, 's-', color=RN_COL, lw=2, ms=7, label='ECGResNetSE')
axes[0,1].fill_between(fold_x, cv_ms, cv_rn,
    where=(cv_ms >= cv_rn), color=GREEN, alpha=0.18, label='MultiScale leads')
axes[0,1].fill_between(fold_x, cv_ms, cv_rn,
    where=(cv_ms < cv_rn),  color=RED,   alpha=0.18, label='ResNetSE leads')
axes[0,1].set_xticks(fold_x)
axes[0,1].set_xticklabels([f'Fold {i}' for i in fold_x], color=TX2)
axes[0,1].set_ylabel('Macro F1', color=TX2)
axes[0,1].set_title('Per-Fold F1 Trend + Difference Shading', color=TX, fontsize=10, fontweight='bold')
axes[0,1].legend(facecolor=PAN, labelcolor=TX, fontsize=9)

# Panel C — McNemar contingency table heatmap
ct = np.array([[both_c, b], [c_cell, both_w]])
im = axes[1,0].imshow(ct, cmap='Blues', aspect='auto')
axes[1,0].set_xticks([0, 1]); axes[1,0].set_yticks([0, 1])
axes[1,0].set_xticklabels(['ResNetSE\ncorrect', 'ResNetSE\nwrong'], color=TX2)
axes[1,0].set_yticklabels(['MultiScale\ncorrect', 'MultiScale\nwrong'], color=TX2)
for (r, cc2), val in np.ndenumerate(ct):
    axes[1,0].text(cc2, r, f'{val:,}', ha='center', va='center',
                  color='white' if val > ct.max()*0.5 else TX, fontsize=14, fontweight='bold')
axes[1,0].set_title(
    f"McNemar's Test  chi2={chi2_stat:.2f}  p={p_val:.2e}  {sig_str}\n"
    f'b={b:,}  c={c_cell:,}  (with continuity correction)',
    color=TX, fontsize=10, fontweight='bold')

# Panel D — per-class McNemar bar chart
if per_class_results:
    cls_labels = [r[0].split('(')[0].strip() for r in per_class_results]
    ms_f1s_pc  = [r[1] for r in per_class_results]
    rn_f1s_pc  = [r[2] for r in per_class_results]
    p_vals_pc  = [r[4] for r in per_class_results]
    xc = np.arange(len(cls_labels)); wc = 0.35
    axes[1,1].bar(xc - wc/2, ms_f1s_pc, wc, color=MS_COL, alpha=0.85,
                  label='MultiScaleECGCNN', zorder=3)
    axes[1,1].bar(xc + wc/2, rn_f1s_pc, wc, color=RN_COL, alpha=0.85,
                  label='ECGResNetSE',      zorder=3)
    for xi, pv in enumerate(p_vals_pc):
        if pv < 0.05:
            ymax = max(ms_f1s_pc[xi], rn_f1s_pc[xi])
            axes[1,1].text(xi, ymax + 0.02, '*', ha='center', color=GREEN,
                          fontsize=16, fontweight='bold')
    axes[1,1].set_xticks(xc)
    axes[1,1].set_xticklabels(cls_labels, color=TX2, rotation=15, ha='right')
    axes[1,1].set_ylabel('Per-Class F1', color=TX2)
    axes[1,1].set_ylim(0, 1.15)
    axes[1,1].set_title(
        'Per-Class McNemar Breakdown\n* = significant difference (p<0.05)',
        color=TX, fontsize=10, fontweight='bold')
    axes[1,1].legend(facecolor=PAN, labelcolor=TX, fontsize=9)

plt.tight_layout()
_pfig = f'{output_dir}/statistical_validation_cv_mcnemar.png'
plt.savefig(_pfig, dpi=300, bbox_inches='tight', facecolor=BG); plt.close()
print(f'\n  [FIGURE] {_pfig}')

# Final summary
print(f"""
================== STATISTICAL VALIDATION SUMMARY ==================
5-FOLD CV (MultiScale vs ResNetSE, {EPOCHS_CV} epochs each):
  MultiScaleECGCNN  {cv_ms.mean():.4f} +/- {cv_ms.std():.4f}  95% CI [{ci_ms[0]:.4f},{ci_ms[1]:.4f}]
  ECGResNetSE       {cv_rn.mean():.4f} +/- {cv_rn.std():.4f}  95% CI [{ci_rn[0]:.4f},{ci_rn[1]:.4f}]
  {wtest_str}

McNEMAR'S TEST ({TEST_SRC}):
  MultiScaleECGCNN  Macro F1={f1_ms_t:.4f}  Boot CI [{ci_ms_b[0]:.4f},{ci_ms_b[1]:.4f}]
  ECGResNetSE       Macro F1={f1_rn_t:.4f}  Boot CI [{ci_rn_b[0]:.4f},{ci_rn_b[1]:.4f}]
  chi2={chi2_stat:.2f}  p={p_val:.2e}  --> {sig_str}
=====================================================================
""")

"""
Bootstrap 95% CIs for accuracy, precision, recall, F1  — SELF-CONTAINED
=======================================================================
Run this in a NEW CELL after Cell 7B (the held-out test evaluation).

It auto-detects your predictions in this order:
  1. all_true_held / all_preds_held   <- created by your Cell 7B
  2. y_true / y_pred                  <- generic names
  3. regenerates them from mitbih_test.csv using `model` + `device`

No model retraining. Runtime: a few seconds.
"""

import numpy as np
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, precision_recall_fscore_support)

# ----------------------------------------------------------------------
# STEP 0 — locate predictions
# ----------------------------------------------------------------------
y_t = y_p = None

if 'all_true_held' in globals() and 'all_preds_held' in globals():
    y_t, y_p = np.asarray(all_true_held), np.asarray(all_preds_held)
    print('[OK] using all_true_held / all_preds_held from Cell 7B')

elif 'y_true' in globals() and 'y_pred' in globals():
    y_t, y_p = np.asarray(y_true), np.asarray(y_pred)
    print('[OK] using y_true / y_pred')

else:
    print('[INFO] predictions not in memory — regenerating from mitbih_test.csv')
    import pandas as pd, torch
    from torch.utils.data import DataLoader, TensorDataset

    KAGGLE_TEST_PATH = '/content/data/kaggle/mitbih_test.csv'
    df_test = pd.read_csv(KAGGLE_TEST_PATH, header=None)
    X_held  = df_test.iloc[:, :187].values.astype(np.float32)
    y_held  = df_test.iloc[:, 187].values.astype(int)

    _m   = model            # trained MultiScaleECGCNN
    _dev = device
    _m.eval()

    ld = DataLoader(TensorDataset(torch.tensor(X_held, dtype=torch.float32),
                                  torch.tensor(y_held, dtype=torch.long)),
                    batch_size=512, shuffle=False)
    P, T = [], []
    with torch.no_grad():
        for xb, yb in ld:
            P.extend(_m(xb.to(_dev)).argmax(1).cpu().numpy())
            T.extend(yb.numpy())
    y_t, y_p = np.array(T), np.array(P)
    print(f'[OK] regenerated predictions for {len(y_t):,} beats')

y_t = np.asarray(y_t).ravel()
y_p = np.asarray(y_p).ravel()
assert y_t.shape == y_p.shape, 'y_true and y_pred lengths differ'

CLASSES = ['Normal (N)', 'Supra (S)', 'PVC (V)', 'Fusion (F)', 'Unknown (Q)']
N_BOOT, SEED = 1000, 42
rng, n = np.random.default_rng(SEED), len(y_t)
print(f'[OK] n = {n:,} beats | bootstrap B = {N_BOOT} | seed = {SEED}\n')

# ----------------------------------------------------------------------
# STEP 1 — resample predictions with replacement
# ----------------------------------------------------------------------
overall = {k: [] for k in
           ['accuracy', 'macro_precision', 'macro_recall', 'macro_f1', 'weighted_f1']}
per_class = {c: {'precision': [], 'recall': [], 'f1': []} for c in CLASSES}
K = len(CLASSES)

for _ in range(N_BOOT):
    idx = rng.integers(0, n, n)
    yt, yp = y_t[idx], y_p[idx]
    overall['accuracy'].append(accuracy_score(yt, yp))
    overall['macro_precision'].append(precision_score(yt, yp, average='macro', zero_division=0))
    overall['macro_recall'].append(recall_score(yt, yp, average='macro', zero_division=0))
    overall['macro_f1'].append(f1_score(yt, yp, average='macro', zero_division=0))
    overall['weighted_f1'].append(f1_score(yt, yp, average='weighted', zero_division=0))
    p, r, f, _ = precision_recall_fscore_support(yt, yp, labels=range(K), zero_division=0)
    for i, c in enumerate(CLASSES):
        per_class[c]['precision'].append(p[i])
        per_class[c]['recall'].append(r[i])
        per_class[c]['f1'].append(f[i])

def ci(v):
    return float(np.percentile(v, 2.5)), float(np.percentile(v, 97.5))

point = {
    'accuracy':        accuracy_score(y_t, y_p),
    'macro_precision': precision_score(y_t, y_p, average='macro', zero_division=0),
    'macro_recall':    recall_score(y_t, y_p, average='macro', zero_division=0),
    'macro_f1':        f1_score(y_t, y_p, average='macro', zero_division=0),
    'weighted_f1':     f1_score(y_t, y_p, average='weighted', zero_division=0),
}

# ----------------------------------------------------------------------
# STEP 2 — report
# ----------------------------------------------------------------------
print('=' * 72)
print(f'  BOOTSTRAP 95% CONFIDENCE INTERVALS   (n={n:,}  B={N_BOOT}  seed={SEED})')
print('=' * 72)
print(f"  {'Metric':18}{'Estimate':>10}{'95% CI':>22}{'width':>9}")
print('  ' + '-' * 60)
for k, v in point.items():
    lo, hi = ci(overall[k])
    print(f'  {k:18}{v:>10.4f}   [{lo:.4f}, {hi:.4f}]{hi-lo:>9.4f}')

print('\n  PER-CLASS  (estimate  [95% CI])')
print('  ' + '-' * 60)
p0, r0, f0, sup = precision_recall_fscore_support(y_t, y_p, labels=range(K), zero_division=0)
for i, c in enumerate(CLASSES):
    pl, ph = ci(per_class[c]['precision'])
    rl, rh = ci(per_class[c]['recall'])
    fl, fh = ci(per_class[c]['f1'])
    print(f'  {c:16} n={sup[i]:>6,}')
    print(f'      precision {p0[i]:.4f}  [{pl:.4f}, {ph:.4f}]')
    print(f'      recall    {r0[i]:.4f}  [{rl:.4f}, {rh:.4f}]')
    print(f'      F1        {f0[i]:.4f}  [{fl:.4f}, {fh:.4f}]')

# ----------------------------------------------------------------------
# STEP 3 — persist
# ----------------------------------------------------------------------
import json, os
os.makedirs('./ecg_results_figures', exist_ok=True)
out = {'n_test': int(n), 'n_bootstrap': N_BOOT, 'seed': SEED,
       'overall': {k: {'estimate': float(point[k]),
                       'ci_low': ci(overall[k])[0],
                       'ci_high': ci(overall[k])[1]} for k in point},
       'per_class': {c: {'support': int(sup[i]),
                         'precision': {'estimate': float(p0[i]), 'ci_low': ci(per_class[c]['precision'])[0], 'ci_high': ci(per_class[c]['precision'])[1]},
                         'recall':    {'estimate': float(r0[i]), 'ci_low': ci(per_class[c]['recall'])[0],    'ci_high': ci(per_class[c]['recall'])[1]},
                         'f1':        {'estimate': float(f0[i]), 'ci_low': ci(per_class[c]['f1'])[0],        'ci_high': ci(per_class[c]['f1'])[1]}}
                     for i, c in enumerate(CLASSES)}}
with open('./ecg_results_figures/bootstrap_cis.json', 'w') as fh:
    json.dump(out, fh, indent=2)
print('\n[SAVED] ./ecg_results_figures/bootstrap_cis.json')
print('[DONE]  Paste the table above back and it will be formatted into the manuscript.')