# -*- coding: utf-8 -*-
"""ECD XAI LIME-2D.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bypFJsA_MsW__ZlWaQ62yvN5KAsoKDOG
"""



# =============================================================================
# LOAD CHECKPOINT — MendeleyResNet (matches Cell NEW-A save format)
# =============================================================================
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

import torch
import torch.nn as nn

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Must match the class in Cell NEW-A exactly
class MendeleyResNet(nn.Module):
    def __init__(self, num_classes=3):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3, 32, 3, padding=1), nn.BatchNorm2d(32), nn.ReLU(True), nn.MaxPool2d(2),
            nn.Conv2d(32, 64, 3, padding=1), nn.BatchNorm2d(64), nn.ReLU(True), nn.MaxPool2d(2),
            nn.Conv2d(64, 128, 3, padding=1), nn.BatchNorm2d(128), nn.ReLU(True), nn.MaxPool2d(2),
            nn.Conv2d(128, 256, 3, padding=1), nn.BatchNorm2d(256), nn.ReLU(True),
            nn.AdaptiveAvgPool2d((4, 4))
        )
        self.classifier = nn.Sequential(
            nn.Dropout(0.5),
            nn.Linear(256 * 4 * 4, 256),
            nn.ReLU(True),
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        )

    def forward(self, x):
        if x.dim() == 4 and x.shape[-1] == 3:
            x = x.permute(0, 3, 1, 2)
        x = x.float()
        if x.max() > 1.0: x = x / 255.0
        return self.classifier(self.features(x).flatten(1))

CKPT_PATH = '/content/drive/MyDrive/ECG_Project_Checkpoints/mendeley_best.pt'

mendeley_model = MendeleyResNet(num_classes=3).to(device)
mendeley_model.load_state_dict(torch.load(CKPT_PATH, map_location=device))
mendeley_model.eval()

print(f'[OK] MendeleyResNet loaded from {CKPT_PATH}')

# =============================================================================
# LOAD MENDELEY IMAGE DATA (data-loading portion of Cell NEW-A only)
# Populates images_all, labels_all — needed by Cell 25 (LIME-2D)
# =============================================================================
import numpy as np
import os
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

mendeley_base  = "/content/data/mendeley"
class_names    = [
    "Normal Person ECG Images (284x12=3408)",
    "ECG Images of Patient that have abnormal heartbeat (233x12=2796)",
    "ECG Images of Myocardial Infarction Patients (240x12=2880)",
]
label_map      = {c: i for i, c in enumerate(class_names)}

images_all, labels_all = [], []
DATA_SOURCE = "SYNTHETIC"

try:
    from PIL import Image as PILImage
    for cls in class_names:
        folder = os.path.join(mendeley_base, cls)
        files  = [f for f in os.listdir(folder) if f.endswith((".png",".jpg",".npy"))]
        if not files: raise FileNotFoundError(f"Empty folder: {folder}")
        for fname in files:
            fp = os.path.join(folder, fname)
            if fname.endswith(".npy"):
                sig = np.load(fp)
                fig_t, ax_t = plt.subplots(figsize=(2.24,2.24),dpi=100)
                ax_t.plot(sig,"k-",lw=1); ax_t.axis("off")
                fig_t.canvas.draw()
                try:
                    buf = np.frombuffer(fig_t.canvas.tostring_rgb(),dtype=np.uint8)
                    buf = buf.reshape(fig_t.canvas.get_width_height()[::-1]+(3,))
                except:
                    fig_t.canvas.draw()
                    buf = np.array(fig_t.canvas.renderer.buffer_rgba())[:,:,:3]
                plt.close(fig_t)
                arr = np.array(PILImage.fromarray(buf).resize((224,224))).astype(np.float32)/255.
            else:
                arr = np.array(PILImage.open(fp).convert("RGB").resize((224,224))).astype(np.float32)/255.
            images_all.append(arr); labels_all.append(label_map[cls])
    DATA_SOURCE = "REAL"
    print(f"[OK] Loaded {len(images_all)} real Mendeley images")
except Exception as _e:
    print(f"[INFO] Mendeley images not found ({_e}) — generating synthetic data")
    np.random.seed(42)
    t_arr = np.linspace(0, 1, 224)
    for cls_i, cls in enumerate(class_names):
        for _ in range(200):
            img = np.ones((224,224,3),dtype=np.float32)*0.96
            wave = 0.3*np.sin(2*np.pi*3*t_arr) + 0.5
            if cls_i==1: wave += 0.15*np.sin(2*np.pi*9*t_arr)
            if cls_i==2: wave[70:150] += 0.25
            wave += np.random.normal(0, 0.02, 224)
            rows = np.clip((wave*224*0.3+224*0.35).astype(int), 0, 223)
            for col, row in enumerate(rows):
                for dr in range(-2,3):
                    img[np.clip(row+dr,0,223), col] = [0.1,0.1,0.1]
            images_all.append(img); labels_all.append(cls_i)
    print(f"[OK] Generated {len(images_all)} synthetic images (200 per class)")

images_all = np.stack(images_all); labels_all = np.array(labels_all)
print(f"Dataset: {images_all.shape}  Labels: {np.bincount(labels_all)}")
print(f"DATA_SOURCE = {DATA_SOURCE}")

# =============================================================================
# CELL 25 — LIME-2D: IMAGE-BASED EXPLANATION FOR MendeleyResNet
# =============================================================================
# Requires: mendeley_model, images_all, labels_all (Cell NEW-A / Cell 10)
# Produces:
#   lime_2d_single_explanation.png   — superpixel overlay for one sample
#   lime_2d_scores_distribution.png  — trust score distribution per class
#   Adds scores to xai_report via report.add_lime_2d_result()
#
# Trust score: fraction of top-K positive superpixels whose centroid column
# falls inside QRS anchor [cols 50-150 of 224-wide image]. Score in [0,1].
# VALID >= 0.40.
# =============================================================================

import numpy as np
import torch
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import os, time, warnings
warnings.filterwarnings('ignore')

try:
    from lime import lime_image
    from skimage.segmentation import quickshift, mark_boundaries
    print('[OK] lime + skimage ready')
except ImportError:
    import subprocess, sys
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'lime', 'scikit-image', '-q'])
    from lime import lime_image
    from skimage.segmentation import quickshift, mark_boundaries
    print('[OK] lime + skimage installed')

output_dir = './ecg_results_figures'
os.makedirs(output_dir, exist_ok=True)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Verify prerequisites
try:
    _ = mendeley_model
    _ = images_all
    _ = labels_all
    print(f'[OK] mendeley_model  images_all={images_all.shape}  labels_all={labels_all.shape}')
except NameError as e:
    raise RuntimeError(f'[FATAL] Run Cell NEW-A (MendeleyResNet training) first: {e}')

# Constants
N_PER_CLASS_2D  = 10      # samples per Mendeley class (randomised)
QRS_COL_LO      = 50     # QRS anchor: pixel column start
QRS_COL_HI      = 150    # QRS anchor: pixel column end
TOP_K_PIXELS    = 5      # top positive superpixels to evaluate
LIME2D_SAMPLES  = 256    # LimeImageExplainer perturbation count
LIME2D_FEATURES = 10     # superpixels in explanation
CLASS_NAMES_2D  = ['Normal', 'Abnormal', 'MI']

# Predict function for LimeImageExplainer
# Input:  (N, 224, 224, 3) float32 uint8
# Output: (N, 3)           float32 softmax probs
def mendeley_predict_fn(images):
    imgs_f = images.astype(np.float32) / 255.0 if images.max() > 1.0 else images.astype(np.float32)
    t = torch.tensor(imgs_f, dtype=torch.float32).to(device)
    with torch.no_grad():
        return torch.softmax(mendeley_model(t), dim=1).cpu().numpy()

# Segmentation tuned for ECG plot images
def _segment_ecg_image(img_rgb):
    return quickshift(img_rgb, kernel_size=4, max_dist=200, ratio=0.2)

# Trust score helper
def _lime2d_trust_score(explanation, pred_class, segments,
                         qrs_lo=QRS_COL_LO, qrs_hi=QRS_COL_HI, top_k=TOP_K_PIXELS):
    if pred_class not in explanation.local_exp:
        keys = list(explanation.local_exp.keys())
        pred_class = keys[0] if keys else -1
    if pred_class == -1:
        return 0.0
    sp_weights  = sorted(explanation.local_exp[pred_class], key=lambda x: -x[1])
    positive_sp = [(sp_id, w) for sp_id, w in sp_weights if w > 0][:top_k]
    if not positive_sp:
        return 0.0
    n_in_qrs = 0
    for sp_id, _ in positive_sp:
        mask = (segments == sp_id)
        if mask.any():
            col_centroid = float(np.where(mask)[1].mean())
            if qrs_lo <= col_centroid <= qrs_hi:
                n_in_qrs += 1
    return float(n_in_qrs) / float(len(positive_sp))

# Run LIME 2D
print('=' * 62)
print('  LIME-2D  |  MendeleyResNet  |  ECG image superpixels')
print(f'  Anchor: columns [{QRS_COL_LO}, {QRS_COL_HI}] of 224-wide image')
print(f'  Top-K: {TOP_K_PIXELS}  |  {N_PER_CLASS_2D} samples/class  |  randomised')
print('=' * 62)

explainer_2d   = lime_image.LimeImageExplainer(random_state=42)
lime_2d_scores = []
lime_2d_labels = []
lime_2d_best   = None
rng_2d         = np.random.default_rng(42)
t0_2d          = time.time()

for cls_i, cls_name in enumerate(CLASS_NAMES_2D):
    cls_idx_arr = np.where(labels_all == cls_i)[0]
    if len(cls_idx_arr) == 0:
        print(f'  {cls_name:<10}: SKIP — no samples')
        continue
    n_run  = min(N_PER_CLASS_2D, len(cls_idx_arr))
    chosen = rng_2d.choice(cls_idx_arr, n_run, replace=False)  # randomised
    cls_scores = []
    t0_cls     = time.time()

    for sample_idx in chosen:
        img_hw3    = images_all[sample_idx]                         # (224,224,3) float [0,1]
        img_hw3_u8 = (np.clip(img_hw3, 0, 1) * 255).astype(np.uint8)

        exp = explainer_2d.explain_instance(
            img_hw3_u8,
            mendeley_predict_fn,
            top_labels      = 3,
            hide_color      = 0,
            num_samples     = LIME2D_SAMPLES,
            segmentation_fn = _segment_ecg_image
        )

        prob     = mendeley_predict_fn(img_hw3[np.newaxis])[0]
        pred_cls = int(np.argmax(prob))
        segs     = _segment_ecg_image(img_hw3_u8)
        score    = _lime2d_trust_score(exp, pred_cls, segs)

        cls_scores.append(score)
        lime_2d_scores.append(score)
        lime_2d_labels.append(cls_i)

        if lime_2d_best is None or score > lime_2d_best[3]:
            lime_2d_best = (img_hw3, exp, segs, score, cls_i, pred_cls)

    print(f'  {cls_name:<10}: mean={np.mean(cls_scores):.4f}  '
          f'std={np.std(cls_scores):.4f}  n={len(cls_scores)}  '
          f'time={time.time()-t0_cls:.0f}s')

lime_2d_scores = np.array(lime_2d_scores)
lime_2d_labels = np.array(lime_2d_labels)
verdict_2d = ('VALID (>=0.40)' if lime_2d_scores.mean() >= 0.40 else
              'REVIEW (>=0.28)' if lime_2d_scores.mean() >= 0.28 else 'FAIL (<0.28)')
print(f'\n  Overall mean={lime_2d_scores.mean():.4f}  std={lime_2d_scores.std():.4f}  '
      f'n={len(lime_2d_scores)}  {verdict_2d}  time={time.time()-t0_2d:.0f}s')

# Register with XAI Trust Report
try:
    for s in lime_2d_scores:
        xai_report.add_lime_2d_result(float(s))
    print(f'  [OK] {len(lime_2d_scores)} scores added to xai_report')
except (NameError, AttributeError):
    print(f'  [INFO] Scores in lime_2d_scores (xai_report not found)')

# Colours
BG = '#0d1117'; PAN = '#161b22'; TX = '#c9d1d9'; TX2 = '#8b949e'
GRID = '#30363d'; GREEN = '#2ea44f'; GOLD = '#d29922'
CLS_COLS_2D = ['#2ea44f', '#58a6ff', '#d29922']

# Figure 1: Single best explanation
if lime_2d_best is not None:
    img_b, exp_b, segs_b, score_b, true_b, pred_b = lime_2d_best
    _, pos_mask = exp_b.get_image_and_mask(pred_b, positive_only=True,
                                            num_features=LIME2D_FEATURES, hide_rest=False)
    _, neg_mask = exp_b.get_image_and_mask(pred_b, positive_only=False,
                                            negative_only=True, num_features=LIME2D_FEATURES,
                                            hide_rest=False)
    overlay = img_b.copy()
    overlay[pos_mask.astype(bool)] = [0.18, 0.60, 0.31]
    overlay[neg_mask.astype(bool)] = [0.90, 0.33, 0.30]

    fig_s, axes_s = plt.subplots(1, 3, figsize=(18, 6), facecolor=BG)
    fig_s.suptitle(
        f'LIME-2D  MendeleyResNet | True: {CLASS_NAMES_2D[true_b]}  '
        f'Pred: {CLASS_NAMES_2D[pred_b]}\n'
        f'Trust score={score_b:.4f}  {verdict_2d}  '
        f'Anchor cols [{QRS_COL_LO},{QRS_COL_HI}]  Top-K={TOP_K_PIXELS}',
        color=TX, fontsize=12, fontweight='bold')
    for ax in axes_s:
        ax.set_facecolor(PAN)
        for sp in ax.spines.values(): sp.set_color(GRID)
        ax.set_xticks([]); ax.set_yticks([])
    axes_s[0].imshow(img_b)
    axes_s[0].set_title('Original ECG Image', color=TX, fontsize=11)
    axes_s[1].imshow(mark_boundaries(img_b, segs_b))
    axes_s[1].axvline(QRS_COL_LO, color=GOLD, lw=2, ls='--')
    axes_s[1].axvline(QRS_COL_HI, color=GOLD, lw=2, ls='--')
    axes_s[1].set_title(f'Quickshift Superpixels  QRS anchor [{QRS_COL_LO},{QRS_COL_HI}]',
                        color=TX, fontsize=11)
    axes_s[2].imshow(mark_boundaries(overlay, segs_b))
    axes_s[2].set_title(f'Attribution Overlay  Green=+  Red=-  score={score_b:.4f}',
                        color=TX, fontsize=11)
    plt.tight_layout()
    p_s = f'{output_dir}/lime_2d_single_explanation.png'
    plt.savefig(p_s, dpi=300, bbox_inches='tight', facecolor=BG); plt.close()
    print(f'  [FIG 1] {p_s}')

# Figure 2: Distribution per class
fig_d, axes_d = plt.subplots(1, 2, figsize=(16, 6), facecolor=BG)
fig_d.suptitle(
    'LIME-2D Score Distribution  MendeleyResNet\n'
    f'Trust = fraction of top-{TOP_K_PIXELS} superpixels inside QRS anchor '
    f'[cols {QRS_COL_LO}-{QRS_COL_HI}]',
    color=TX, fontsize=12, fontweight='bold')
for ax in axes_d:
    ax.set_facecolor(PAN)
    for sp in ax.spines.values(): sp.set_color(GRID)
    ax.tick_params(colors=TX2); ax.grid(color=GRID, lw=0.4, alpha=0.5)
for ci, (cn, cc) in enumerate(zip(CLASS_NAMES_2D, CLS_COLS_2D)):
    m = (lime_2d_labels == ci)
    if m.sum() > 1:
        axes_d[0].hist(lime_2d_scores[m], bins=8, color=cc, alpha=0.65,
                       label=f'{cn} (n={m.sum()})', zorder=3)
axes_d[0].axvline(0.28, color=GOLD, ls=':', lw=1.5, label='0.28 REVIEW')
axes_d[0].axvline(0.40, color=GREEN, ls='--', lw=2, label='0.40 VALID')
axes_d[0].axvline(lime_2d_scores.mean(), color=TX, ls='-.', lw=2,
                   label=f'mean={lime_2d_scores.mean():.4f}')
axes_d[0].set_xlabel('LIME-2D Trust Score', color=TX2, fontsize=11)
axes_d[0].set_ylabel('Count', color=TX2)
axes_d[0].set_title('Score Distribution by Class', color=TX, fontsize=11, fontweight='bold')
axes_d[0].legend(facecolor=PAN, labelcolor=TX, fontsize=9)
cls_means_2d = []
cls_stds_2d  = []
for ci in range(3):
    m = (lime_2d_labels == ci)
    cls_means_2d.append(lime_2d_scores[m].mean() if m.sum() > 0 else 0.0)
    cls_stds_2d.append(lime_2d_scores[m].std()   if m.sum() > 0 else 0.0)
bars_d = axes_d[1].bar(range(3), cls_means_2d, color=CLS_COLS_2D, alpha=0.85,
                        zorder=3, yerr=cls_stds_2d, capsize=6,
                        error_kw={'color': TX, 'lw': 1.5})
for bar, val, std in zip(bars_d, cls_means_2d, cls_stds_2d):
    verd = 'OK' if val >= 0.40 else 'REVIEW' if val >= 0.28 else 'FAIL'
    axes_d[1].text(bar.get_x()+bar.get_width()/2, val+std+0.03,
                   f'{val:.4f}\n{verd}', ha='center', color=TX,
                   fontsize=10, fontweight='bold')
axes_d[1].axhline(0.28, color=GOLD, ls=':', lw=1.5, label='0.28 REVIEW')
axes_d[1].axhline(0.40, color=GREEN, ls='--', lw=2, label='0.40 VALID')
axes_d[1].set_xticks(range(3)); axes_d[1].set_xticklabels(CLASS_NAMES_2D, color=TX2)
axes_d[1].set_ylabel('Mean LIME-2D Trust Score', color=TX2)
axes_d[1].set_ylim(0, 1.0)
axes_d[1].set_title('Per-Class Mean +/- Std', color=TX, fontsize=11, fontweight='bold')
axes_d[1].legend(facecolor=PAN, labelcolor=TX, fontsize=9)
plt.tight_layout()
p_d = f'{output_dir}/lime_2d_scores_distribution.png'
plt.savefig(p_d, dpi=300, bbox_inches='tight', facecolor=BG); plt.close()
print(f'  [FIG 2] {p_d}')

print('\nLIME-2D complete.')
print(f'  Overall  mean={lime_2d_scores.mean():.4f}  std={lime_2d_scores.std():.4f}  n={len(lime_2d_scores)}')
for ci, cn in enumerate(CLASS_NAMES_2D):
    m = (lime_2d_labels == ci)
    if m.sum() > 0:
        print(f'  {cn:<10}: mean={lime_2d_scores[m].mean():.4f} +/- {lime_2d_scores[m].std():.4f}')

[OK] lime + skimage ready
[OK] mendeley_model  images_all=(756, 224, 224, 3)  labels_all=(756,)
==============================================================
  LIME-2D  |  MendeleyResNet  |  ECG image superpixels
  Anchor: columns [50, 150] of 224-wide image
  Top-K: 5  |  10 samples/class  |  randomised
==============================================================
100% 256/256 [00:01<00:00, 252.00it/s]100% 256/256 [00:00<00:00, 268.23it/s]100% 256/256 [00:00<00:00, 266.21it/s]100% 256/256 [00:01<00:00, 254.77it/s]100% 256/256 [00:01<00:00, 187.03it/s]100% 256/256 [00:00<00:00, 253.24it/s]100% 256/256 [00:00<00:00, 265.70it/s]100% 256/256 [00:00<00:00, 252.13it/s]100% 256/256 [00:00<00:00, 258.94it/s]100% 256/256 [00:01<00:00, 256.04it/s]  Normal    : mean=0.4400  std=0.1960  n=10  time=23s
100% 256/256 [00:01<00:00, 148.05it/s]100% 256/256 [00:00<00:00, 266.62it/s]100% 256/256 [00:00<00:00, 264.43it/s]100% 256/256 [00:00<00:00, 264.28it/s]100% 256/256 [00:01<00:00, 252.56it/s]100% 256/256 [00:01<00:00, 245.71it/s]100% 256/256 [00:01<00:00, 192.79it/s]100% 256/256 [00:01<00:00, 255.62it/s]100% 256/256 [00:00<00:00, 260.51it/s]100% 256/256 [00:00<00:00, 260.42it/s]  Abnormal  : mean=0.0000  std=0.0000  n=10  time=24s
100% 256/256 [00:00<00:00, 262.58it/s]100% 256/256 [00:01<00:00, 255.77it/s]100% 256/256 [00:01<00:00, 175.45it/s]100% 256/256 [00:01<00:00, 232.32it/s]100% 256/256 [00:01<00:00, 250.06it/s]100% 256/256 [00:00<00:00, 258.50it/s]100% 256/256 [00:00<00:00, 266.24it/s]100% 256/256 [00:01<00:00, 253.58it/s]100% 256/256 [00:01<00:00, 181.70it/s]100% 256/256 [00:01<00:00, 182.53it/s]  MI        : mean=0.6200  std=0.1077  n=10  time=24s

  Overall mean=0.3533  std=0.2907  n=30  REVIEW (>=0.28)  time=72s
  [INFO] Scores in lime_2d_scores (xai_report not found)
      [+pdf] lime_2d_single_explanation.pdf
  [FIG 1] ./ecg_results_figures/lime_2d_single_explanation.png
      [+pdf] lime_2d_scores_distribution.pdf
  [FIG 2] ./ecg_results_figures/lime_2d_scores_distribution.png

LIME-2D complete.
  Overall  mean=0.3533  std=0.2907  n=30
  Normal    : mean=0.4400 +/- 0.1960
  Abnormal  : mean=0.0000 +/- 0.0000
  MI        : mean=0.6200 +/- 0.1077