# -*- coding: utf-8 -*-
"""ECG ABLATION STUDY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cJUWTFojpaLjxqwtwwdr3NkojlMbHcPC
"""



# =============================================================================
# CELL NEW-D — ABLATION STUDY (CORRECTED)
# Isolates contribution of: SMOTE | SE blocks | Multi-scale paths | Augmentation
#
# Fixes vs. previous version:
#   1. "No SMOTE" branch previously trained on X_val[:5000] (a 5000-row slice
#      of the *validation* set) instead of a real imbalanced training pool of
#      comparable size to the other variants. That confounded "no SMOTE" with
#      "much smaller training set" and produced a near-3-second run collapsing
#      to F1=0.2552. Fixed below by bootstrap-resampling the real imbalanced
#      pool up to the SAME total N as the balanced pool, preserving natural
#      class proportions — so only the balancing mechanism differs, not the
#      amount of data or number of training steps.
#   2. Delta print had a hardcoded literal "-" in front of an already-signed
#      value, turning small positive deltas (component hurt performance) into
#      "--0.0131" instead of "+0.0131". Fixed with a proper signed format.
#   3. Single run per variant gave no way to tell architecture effect from
#      run-to-run noise. Fixed by running N_SEEDS repeats per variant and
#      reporting mean +/- std.
# =============================================================================
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset, Dataset
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import warnings, os, time
warnings.filterwarnings("ignore")

device     = torch.device("cuda" if torch.cuda.is_available() else "cpu")
output_dir = "./ecg_results_figures"
os.makedirs(output_dir, exist_ok=True)

N_SEEDS = 3  # bump to 5 if you have time; 3 is the minimum for a real std

# ── Shared SE block ───────────────────────────────────────────────────────────
class SEBlock1D_ab(nn.Module):
    def __init__(self, ch, r=8):
        super().__init__()
        self.pool = nn.AdaptiveAvgPool1d(1)
        self.fc   = nn.Sequential(
            nn.Linear(ch,max(ch//r,4),bias=False), nn.ReLU(True),
            nn.Linear(max(ch//r,4),ch,bias=False), nn.Sigmoid())
    def forward(self, x):
        b,c,_ = x.shape
        return x * self.fc(self.pool(x).view(b,c)).view(b,c,1)

# ── Variant 2: No SE block ────────────────────────────────────────────────────
class MultiScaleECGCNN_noSE(nn.Module):
    def __init__(self, num_classes=5, dropout=0.5):
        super().__init__()
        ch = 48
        def _p(k):
            return nn.Sequential(
                nn.Conv1d(1,ch,k,padding=k//2,bias=False),nn.BatchNorm1d(ch),nn.ReLU(True),
                nn.Dropout(dropout*0.5),
                nn.Conv1d(ch,ch,k,padding=k//2,bias=False),nn.BatchNorm1d(ch),nn.ReLU(True),
                nn.AdaptiveAvgPool1d(32))
        self.path_small  = _p(3)
        self.path_medium = _p(9)
        self.path_large  = _p(21)
        mc = ch*3
        # NO SE block here
        self.fusion     = nn.Sequential(
            nn.Dropout(dropout*0.6), nn.Conv1d(mc,96,3,padding=1,bias=False),
            nn.BatchNorm1d(96), nn.ReLU(True), nn.AdaptiveAvgPool1d(1))
        self.classifier = nn.Sequential(
            nn.Dropout(dropout), nn.Linear(96,64), nn.ReLU(True),
            nn.Dropout(dropout*0.5), nn.Linear(64,num_classes))
    def forward(self, x):
        if x.dim()==2: x=x.unsqueeze(1)
        f = torch.cat([self.path_small(x),self.path_medium(x),self.path_large(x)],1)
        return self.classifier(self.fusion(f).squeeze(-1))

# ── Variant 3: Single-scale only (kernel=9 only) ─────────────────────────────
class SingleScaleECGCNN(nn.Module):
    def __init__(self, num_classes=5, dropout=0.5):
        super().__init__()
        ch = 48*3   # same param budget as 3 paths
        self.features = nn.Sequential(
            nn.Conv1d(1,ch,9,padding=4,bias=False), nn.BatchNorm1d(ch), nn.ReLU(True),
            nn.Dropout(dropout*0.5),
            nn.Conv1d(ch,ch,9,padding=4,bias=False), nn.BatchNorm1d(ch), nn.ReLU(True),
            nn.AdaptiveAvgPool1d(32))
        mc = ch
        self.se         = SEBlock1D_ab(mc)
        self.fusion     = nn.Sequential(
            nn.Dropout(dropout*0.6), nn.Conv1d(mc,96,3,padding=1,bias=False),
            nn.BatchNorm1d(96), nn.ReLU(True), nn.AdaptiveAvgPool1d(1))
        self.classifier = nn.Sequential(
            nn.Dropout(dropout), nn.Linear(96,64), nn.ReLU(True),
            nn.Dropout(dropout*0.5), nn.Linear(64,num_classes))
    def forward(self, x):
        if x.dim()==2: x=x.unsqueeze(1)
        return self.classifier(self.fusion(self.se(self.features(x))).squeeze(-1))

# ── Variants 4 & 5: Full model (with / without augmentation) ─────────────────
class MultiScaleECGCNN_v2_ab(nn.Module):
    def __init__(self, num_classes=5, dropout=0.5):
        super().__init__()
        ch = 48
        def _p(k):
            return nn.Sequential(
                nn.Conv1d(1,ch,k,padding=k//2,bias=False),nn.BatchNorm1d(ch),nn.ReLU(True),
                nn.Dropout(dropout*0.5),
                nn.Conv1d(ch,ch,k,padding=k//2,bias=False),nn.BatchNorm1d(ch),nn.ReLU(True),
                nn.AdaptiveAvgPool1d(32))
        self.path_small  = _p(3)
        self.path_medium = _p(9)
        self.path_large  = _p(21)
        mc = ch*3
        self.se         = SEBlock1D_ab(mc)
        self.fusion     = nn.Sequential(
            nn.Dropout(dropout*0.6),nn.Conv1d(mc,96,3,padding=1,bias=False),
            nn.BatchNorm1d(96),nn.ReLU(True),nn.AdaptiveAvgPool1d(1))
        self.classifier = nn.Sequential(
            nn.Dropout(dropout),nn.Linear(96,64),nn.ReLU(True),
            nn.Dropout(dropout*0.5),nn.Linear(64,num_classes))
    def forward(self, x):
        if x.dim()==2: x=x.unsqueeze(1)
        f = torch.cat([self.path_small(x),self.path_medium(x),self.path_large(x)],1)
        return self.classifier(self.fusion(self.se(f)).squeeze(-1))

# ── Data preparation ──────────────────────────────────────────────────────────
try:
    _xv = X_val
    X_bal = np.concatenate([X_train, X_val])
    y_bal = np.concatenate([y_train, y_val])

    # --- FIX: build a real imbalanced pool at the SAME total size as X_bal ---
    # X_val was never SMOTE'd (per the split-then-balance protocol), so its
    # class proportions reflect the true imbalanced distribution. Bootstrap
    # (sample-with-replacement) it up to len(X_bal) total rows, preserving its
    # natural class ratios. This equalizes total N and number of training
    # steps between "No SMOTE" and every other variant, so the only thing
    # that differs is whether classes were balanced before training.
    rng = np.random.default_rng(42)
    target_n = len(X_bal)
    idx = rng.choice(len(X_val), size=target_n, replace=True)
    X_imb, y_imb = X_val[idx], y_val[idx]

    print(f"[OK] Real data  X_bal={X_bal.shape}  X_imb(bootstrapped, same N, "
          f"natural class ratio)={X_imb.shape}")
    from collections import Counter
    print(f"     X_imb class counts: {dict(Counter(y_imb.tolist()))}")
except NameError:
    print("[INFO] Generating synthetic balanced data for ablation")
    np.random.seed(42)
    t_arr = np.linspace(0,1,187)
    X_bal, y_bal = [], []
    for cls in range(5):
        for _ in range(1000):
            sig = (np.exp(-((t_arr-0.45)**2)/(2*0.01**2)) +
                   0.15*np.exp(-((t_arr-0.20)**2)/(2*0.015**2)) +
                   0.3*np.exp(-((t_arr-0.65)**2)/(2*0.030**2)) +
                   np.random.normal(0,0.05,187))
            if cls==1: sig += 0.3*np.sin(2*np.pi*5*t_arr)
            if cls==2: sig[80:110]*=0.4
            X_bal.append(sig.astype(np.float32)); y_bal.append(cls)
    X_bal = np.array(X_bal); y_bal = np.array(y_bal)
    # Imbalanced: 10x more class 0, bootstrapped to same total N as X_bal
    rng = np.random.default_rng(42)
    base_imb_X = np.concatenate([X_bal[y_bal==0][:800], X_bal[y_bal!=0]])
    base_imb_y = np.concatenate([y_bal[y_bal==0][:800], y_bal[y_bal!=0]])
    idx = rng.choice(len(base_imb_X), size=len(X_bal), replace=True)
    X_imb, y_imb = base_imb_X[idx], base_imb_y[idx]

class NoAugDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.long)
    def __len__(self): return len(self.y)
    def __getitem__(self, i): return self.X[i], self.y[i]

class AugDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.long)
    def __len__(self): return len(self.y)
    def __getitem__(self, i):
        x = self.X[i] + 0.02*torch.randn_like(self.X[i])
        x = x * (0.8 + 0.4*torch.rand(1))
        return x, self.y[i]

EPOCHS_AB = 10
BATCH_AB  = 256

def set_seed(seed):
    torch.manual_seed(seed)
    np.random.seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

def train_eval(model_fn, X_tr, y_tr, X_vl, y_vl, aug=False, seed=0):
    set_seed(seed)
    tr_ds = AugDataset(X_tr, y_tr) if aug else NoAugDataset(X_tr, y_tr)
    vl_ds = NoAugDataset(X_vl, y_vl)
    tr_ld = DataLoader(tr_ds, batch_size=BATCH_AB, shuffle=True, drop_last=True)
    vl_ld = DataLoader(vl_ds, batch_size=BATCH_AB, shuffle=False)
    m   = model_fn().to(device)
    opt = torch.optim.AdamW(m.parameters(), lr=1e-3, weight_decay=1e-3)
    sch = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=EPOCHS_AB)
    crit= nn.CrossEntropyLoss(label_smoothing=0.1)
    for ep in range(EPOCHS_AB):
        m.train()
        for xb, yb in tr_ld:
            xb,yb = xb.to(device), yb.to(device)
            opt.zero_grad(); crit(m(xb),yb).backward(); opt.step()
        sch.step()
    m.eval()
    preds, trues = [], []
    with torch.no_grad():
        for xb, yb in vl_ld:
            preds.extend(m(xb.to(device)).argmax(1).cpu().numpy())
            trues.extend(yb.numpy())
    return f1_score(trues, preds, average="macro", zero_division=0)

X_tr, X_vl, y_tr, y_vl = train_test_split(X_bal, y_bal, test_size=0.2,
                                             stratify=y_bal, random_state=42)
X_ti, X_vi, y_ti, y_vi = train_test_split(X_imb, y_imb, test_size=0.2,
                                             stratify=y_imb, random_state=42)

# ── Run ablations (N_SEEDS repeats each) ───────────────────────────────────────
print("\n" + "="*70)
print(f"  ABLATION STUDY  (each variant: {N_SEEDS} seeds x {EPOCHS_AB} epochs)")
print("="*70)

ablations = [
    ("No SMOTE (imbalanced data)",   lambda: MultiScaleECGCNN_v2_ab(), X_ti, y_ti, X_vi, y_vi, False),
    ("No SE block",                  lambda: MultiScaleECGCNN_noSE(),   X_tr, y_tr, X_vl, y_vl, True),
    ("Single-scale (k=9 only)",      lambda: SingleScaleECGCNN(),       X_tr, y_tr, X_vl, y_vl, True),
    ("No augmentation",              lambda: MultiScaleECGCNN_v2_ab(), X_tr, y_tr, X_vl, y_vl, False),
    ("Full model (all components)",  lambda: MultiScaleECGCNN_v2_ab(), X_tr, y_tr, X_vl, y_vl, True),
]

results = []  # (name, mean_f1, std_f1, mean_elapsed)
for name, model_fn, xtr, ytr, xvl, yvl, aug in ablations:
    seed_f1s, seed_times = [], []
    for s in range(N_SEEDS):
        t0 = time.time()
        f1 = train_eval(model_fn, xtr, ytr, xvl, yvl, aug=aug, seed=100 + s)
        seed_times.append(time.time() - t0)
        seed_f1s.append(f1)
    mean_f1, std_f1 = float(np.mean(seed_f1s)), float(np.std(seed_f1s))
    mean_t = float(np.mean(seed_times))
    results.append((name, mean_f1, std_f1, mean_t))
    marker = "  <-- FULL MODEL" if "Full" in name else ""
    print(f"  {name:<38}  F1={mean_f1:.4f} +/- {std_f1:.4f}  "
          f"(runs={seed_f1s}, ~{mean_t:.0f}s/run){marker}")

# ── Contribution deltas (FIXED sign/formatting) ────────────────────────────────
full_name, full_f1, full_std, _ = results[-1]
print(f"\n  Component contribution (delta from full model, F1={full_f1:.4f}):")
print("  " + "-"*66)
print("  Positive delta = removing this component HURT performance (component helps)")
print("  Negative delta = removing this component IMPROVED performance (component hurts)")
print("  " + "-"*66)
for name, f1, std, _ in results[:-1]:
    delta = full_f1 - f1                       # + means variant is worse than full
    combined_std = float(np.sqrt(std**2 + full_std**2))
    verdict = "helps" if delta > combined_std else (
              "hurts" if delta < -combined_std else "no clear effect (within noise)")
    print(f"  {name:<38}  delta={delta:+.4f}  ({delta*100:+.2f} pts)  "
          f"combined_std={combined_std:.4f}  -> {verdict}")

# ── Plot ──────────────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(16, 6), facecolor="#0d1117")
fig.suptitle("Ablation Study — Component Contribution Analysis "
             f"(mean +/- std, n={N_SEEDS} seeds)",
             color="#f0f6fc", fontsize=14, fontweight="bold")

for ax in axes:
    ax.set_facecolor("#161b22")
    for sp in ax.spines.values(): sp.set_color("#30363d")
    ax.tick_params(colors="#8b949e")
    ax.grid(color="#30363d", lw=0.4, alpha=0.5, axis="x")

names_ab = [r[0] for r in results]
f1s_ab   = [r[1] for r in results]
stds_ab  = [r[2] for r in results]
colors_ab = ["#58a6ff"]*4 + ["#2ea44f"]

# Left — horizontal F1 bar with error bars
bars = axes[0].barh(names_ab, f1s_ab, xerr=stds_ab, color=colors_ab, height=0.55,
                     zorder=3, capsize=4, ecolor="#f0f6fc")
axes[0].axvline(full_f1, color="#d29922", ls="--", lw=1.5, label=f"Full model F1={full_f1:.4f}")
for bar, val in zip(bars, f1s_ab):
    axes[0].text(val+0.005, bar.get_y()+bar.get_height()/2,
                 f"{val:.4f}", va="center", color="#f0f6fc", fontsize=10, fontweight="bold")
axes[0].set_xlabel("Macro F1", color="#8b949e", fontsize=12)
axes[0].set_xlim(max(0, min(f1s_ab)-0.08), min(1.0, max(f1s_ab)+0.08))
axes[0].set_title("Ablation F1 Scores", color="#c9d1d9", fontsize=11)
axes[0].set_yticklabels(names_ab, color="#c9d1d9", fontsize=9)
axes[0].legend(facecolor="#161b22", labelcolor="#c9d1d9", fontsize=9)

# Right — signed delta contribution (correctly signed, not forced negative)
deltas = [full_f1 - f1 for name, f1, std, _ in results[:-1]]
combined_stds = [float(np.sqrt(std**2 + full_std**2)) for name, f1, std, _ in results[:-1]]
comps  = ["SMOTE\nremoval", "SE block\nremoval", "Multi-scale\nremoval", "Augmentation\nremoval"]
bars2  = axes[1].bar(comps, deltas, yerr=combined_stds, capsize=4, ecolor="#f0f6fc",
                     color=["#e5534b" if d > 0.01 else ("#2ea44f" if d < -0.01 else "#d29922")
                            for d in deltas],
                     width=0.5, zorder=3)
axes[1].axhline(0, color="#8b949e", lw=1)
for bar, val in zip(bars2, deltas):
    axes[1].text(bar.get_x()+bar.get_width()/2, val + (0.002 if val >= 0 else -0.006),
                 f"{val:+.4f}", ha="center", color="#f0f6fc", fontsize=11, fontweight="bold")
axes[1].set_ylabel("F1 delta from full model (+ = component helps)", color="#8b949e", fontsize=11)
axes[1].set_title("Component Contribution", color="#c9d1d9", fontsize=10)
axes[1].set_xticklabels(comps, color="#c9d1d9", fontsize=9)

plt.tight_layout()
plt.savefig(f"{output_dir}/ablation_study.png", dpi=300, bbox_inches="tight", facecolor="#0d1117")
plt.close()
print(f"\nSaved: {output_dir}/ablation_study.png")
print("[DONE] Ablation study complete")