# -*- coding: utf-8 -*-
"""ECG XAI Lime_1D.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eCQFhW3hWbLQNy316dG4MJHBobusCqHf
"""



# =============================================================================
# CELL LIME-1D CLASS-SPECIFIC ADAPTIVE TUNING
# =============================================================================

# =============================================================================

import numpy as np
import torch
import torch.nn.functional as F
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import warnings, os, time
from scipy import stats as scipy_stats
warnings.filterwarnings("ignore")

try:
    import lime, lime.lime_tabular
    print("[OK] lime ready")
except ImportError:
    import subprocess, sys
    subprocess.check_call([sys.executable, "-m", "pip", "install", "lime", "-q"])
    import lime, lime.lime_tabular

output_dir = "./ecg_results_figures"
os.makedirs(output_dir, exist_ok=True)
device    = torch.device("cuda" if torch.cuda.is_available() else "cpu")
INPUT_LEN = 187
LIME_RUNS = 3       # average this many LIME runs per sample
T_MAX     = 15.0    # hard cap on temperature; T>15 -> near-uniform softmax

# Set True to use X_val[200:] background (leak-free but needs recalibrated targets)
# Set False to use X_train[:3000] (v5.3 default, well-calibrated temperatures)
USE_VAL_BACKGROUND = False

# =============================================================================
# CLASS-SPECIFIC CONFIGURATION TABLE
# =============================================================================
CLASS_CFG = {
    0: {"name": "Normal",
        "qrs":       (60, 125),
        "T_range":   (2.0, 30.0),
        "n_samples": 4000,
        "kw_scale":  0.23,
        "note": "Standard QRS complex -- narrow, well-defined"},

    1: {"name": "Supraventricular",
        "qrs":       (15, 85),          # fallback if dynamic anchor fails
                                         # NOTE: display-only label; the anchor
                                         # actually used at scoring time is
                                         # per-sample via _dynamic_pwave_anchor()
                                         # (dynamic hit, or static (20,110) miss)
        "T_range":   (3.0, 25.0),
        "n_samples": 4000,
        "kw_scale":  0.28,
        "dynamic_anchor": True,
        "note": "Extra P-wave + early QRS -- P-wave anchor localised per sample"},

    2: {"name": "PVC",
        "qrs":       (50, 130),
        "T_range":   (2.0, 20.0),
        "n_samples": 3000,
        "kw_scale":  0.32,
        "note": "Wide, inverted QRS -- broadened QRS is primary diagnostic feature"},

    3: {"name": "Fusion",
        "qrs":       (60, 130),
        "T_range":   (4.0, 30.0),
        "n_samples": 3000,
        "kw_scale":  0.35,
        "note": "Two overlapping QRS complexes -- widened diagnostic region"},

    4: {"name": "Unknown",
        "qrs":       (0, 186),
        "T_range":   (3.0, 25.0),
        "n_samples": 2000,
        "kw_scale":  0.30,
        "note": "No fixed morphology -- diagnostic only; excluded from all tiers"},
}

print("CLASS-SPECIFIC LIME CONFIGURATION:")
print(f"  {'Class':<18} {'QRS anchor':<14} {'n_samples':<12} {'kw_scale':<10} Note")
print("  " + "-"*80)
for c, cfg in CLASS_CFG.items():
    qrs_label = "per-sample*" if cfg.get("dynamic_anchor") else str(cfg['qrs'])
    print(f"  {cfg['name']:<18} {qrs_label:<14} {cfg['n_samples']:<12} "
          f"{cfg['kw_scale']:<10} {cfg['note']}")
print("  * dynamic P-wave anchor per sample; static fallback=(20,110)")

# =============================================================================
# STEP 1 -- Load model
# =============================================================================
try:
    _lime_model = model
    _lime_model.eval()
    _lime_model.to(device)
    print(f"\n[OK] model ({sum(p.numel() for p in _lime_model.parameters()):,} params)")
except NameError:
    print("[FATAL] run Cell 17 first"); raise

# =============================================================================
# STEP 2 -- Load data  [FIX #1: stratified by true label, not a raw slice]
# =============================================================================
try:
    if USE_VAL_BACKGROUND:
        _X_bg_all = X_val[200:].astype(np.float32)
        bg_source = "X_val[200:] (leak-free)"
        if len(_X_bg_all) < 200:
            print("[WARN] val background too small -- switch USE_VAL_BACKGROUND=False")
    else:
        _X_bg_all = X_train[:3000].astype(np.float32)
        bg_source = "X_train[:3000]"

    # FIX #1: stratified draw by TRUE label, so rare classes (Supraventricular,
    # Fusion) get enough representation to produce a meaningful sample size
    # after prediction -- an unstratified X_val[:200] slice previously starved
    # these classes down to n=1 predicted sample each.
    _rng_strat = np.random.default_rng(42)
    _X_test_parts, _y_test_parts = [], []
    PER_CLASS_TARGET = 60  # aim for enough per true-class to yield ~10+ predicted samples later

    _y_val_arr = np.array(y_val)
    for _cls in range(5):
        _cls_idx_all = np.where(_y_val_arr == _cls)[0]
        _take = min(PER_CLASS_TARGET, len(_cls_idx_all))
        if _take == 0:
            continue
        _chosen = _rng_strat.choice(_cls_idx_all, _take, replace=False)
        _X_test_parts.append(X_val[_chosen])
        _y_test_parts.append(_y_val_arr[_chosen])

    _X_test_all = np.concatenate(_X_test_parts).astype(np.float32)
    _y_test_all = np.concatenate(_y_test_parts)

    print(f"[OK] data  bg={_X_bg_all.shape} ({bg_source})  "
          f"test={_X_test_all.shape} (stratified by true label)")
    print(f"[OK] true-label counts in test set: "
          f"{dict(zip(*np.unique(_y_test_all, return_counts=True)))}")
except NameError:
    print("[FATAL] run Cell 6/7 first"); raise

def _raw_pred(X):
    t = torch.tensor(X, dtype=torch.float32).to(device)
    with torch.no_grad():
        return _lime_model(t).argmax(dim=1).cpu().numpy()

_pred_classes = _raw_pred(_X_test_all)
print(f"\nPredicted class distribution across {len(_X_test_all)} test samples:")
for c, cfg in CLASS_CFG.items():
    n = int((_pred_classes == c).sum())
    print(f"  {cfg['name']:<18}: {n} samples")

# =============================================================================
# STEP 3 -- Per-class temperature auto-tuning
# =============================================================================
print("\n" + "="*62)
print("  PER-CLASS TEMPERATURE TUNING")
print(f"  [target_min=0.65  target_max=0.90  T_MAX={T_MAX}]")
print("="*62)

def _make_pf(T):
    def _pf(x: np.ndarray) -> np.ndarray:
        t = torch.tensor(x.astype(np.float32)).to(device)
        with torch.no_grad():
            return F.softmax(_lime_model(t) / T, dim=1).cpu().numpy()
    return _pf

def _tune_temperature(X_class_samples, T_range,
                      target_min=0.65, target_max=0.90):
    samples = X_class_samples[:min(20, len(X_class_samples))]
    T_vals  = np.geomspace(T_range[0], min(T_range[1], T_MAX), 20)
    confs   = [float(_make_pf(T)(samples).max(axis=1).mean()) for T in T_vals]

    in_range = [(i, abs(c - target_min))
                for i, c in enumerate(confs)
                if target_min <= c <= target_max]
    if in_range:
        best_i = min(in_range, key=lambda v: v[1])[0]
    else:
        best_i = int(np.argmin([abs(c - target_min) for c in confs]))

    best_T = float(min(T_vals[best_i], T_MAX))
    return best_T, confs[best_i]

CLASS_PARAMS = {}

for cls_idx, cfg in CLASS_CFG.items():
    cls_mask    = (_pred_classes == cls_idx)
    cls_samples = _X_test_all[cls_mask]

    if len(cls_samples) == 0:
        T_best, conf = 5.0, 0.70
        print(f"  {cfg['name']:<18}: no samples -- using default T={T_best}")
    else:
        T_best, conf = _tune_temperature(cls_samples, cfg["T_range"])
        print(f"  {cfg['name']:<18}: T={T_best:.2f}  mean_conf={conf:.4f}  "
              f"n={len(cls_samples)}"
              + ("  [T capped]" if T_best >= T_MAX - 0.01 else ""))

    kw = cfg["kw_scale"] * np.sqrt(INPUT_LEN)
    CLASS_PARAMS[cls_idx] = {
        "T":              T_best,
        "pf":             _make_pf(T_best),
        "n_samples":      cfg["n_samples"],
        "kw":             kw,
        "qrs":            cfg["qrs"],
        "name":           cfg["name"],
        "n_test":         len(cls_samples),
        "dynamic_anchor": cfg.get("dynamic_anchor", False),
    }

# =============================================================================
# STEP 4 -- Build one LIME explainer per class
# =============================================================================
print("\n" + "="*62)
print("  BUILDING CLASS-SPECIFIC EXPLAINERS")
print("="*62)

CLASS_EXPLAINERS = {}

for cls_idx, params in CLASS_PARAMS.items():
    bg_pred = _raw_pred(_X_bg_all)
    bg_mask = (bg_pred == cls_idx)
    if bg_mask.sum() >= 50:
        bg_data = _X_bg_all[bg_mask][:500]
        bg_src  = f"class-specific ({bg_mask.sum()} samples)"
    else:
        bg_data = _X_bg_all[:500]
        bg_src  = "global fallback"

    exp = lime.lime_tabular.LimeTabularExplainer(
        training_data         = bg_data.astype(np.float32),
        feature_names         = [f"t{i}" for i in range(INPUT_LEN)],
        mode                  = "classification",
        discretize_continuous = False,
        kernel_width          = params["kw"],
        random_state          = 42
    )
    CLASS_EXPLAINERS[cls_idx] = exp
    print(f"  {params['name']:<18}: kw={params['kw']:.2f}  bg={bg_src}")

# =============================================================================
# STEP 5 -- Helpers
# =============================================================================

def _dynamic_pwave_anchor(x: np.ndarray,
                           search_start=15,
                           search_end=120,
                           half_width=35,
                           min_amplitude_frac=0.05,
                           min_anchor_width=20):
    """
    Locate P-wave anchor dynamically for Supraventricular samples.
    Returns (lo, hi, method) where method is 'dynamic' or 'fallback'.
    """
    FALLBACK = (20, 110, "fallback")

    qrs_peak_t   = int(np.argmax(np.abs(x)))
    qrs_peak_amp = float(np.abs(x[qrs_peak_t]))

    pre_start = max(search_start, 0)
    pre_end   = min(qrs_peak_t, search_end)

    if pre_end <= pre_start + 5:
        return FALLBACK

    segment = x[pre_start:pre_end]

    candidates = []
    for i in range(1, len(segment) - 1):
        if (segment[i] > segment[i-1] and
                segment[i] > segment[i+1] and
                abs(segment[i]) > min_amplitude_frac * qrs_peak_amp):
            candidates.append((float(segment[i]), pre_start + i))

    if not candidates:
        return FALLBACK

    _, pwave_t = max(candidates, key=lambda v: v[0])
    lo = max(0, pwave_t - half_width)
    hi = min(INPUT_LEN - 1, pwave_t + half_width)

    if (hi - lo) < min_anchor_width:
        return FALLBACK

    return (int(lo), int(hi), "dynamic")


def _entropy_concentration(attr: np.ndarray) -> float:
    attr_norm   = np.abs(attr) / (np.abs(attr).sum() + 1e-8)
    entropy     = -np.sum(attr_norm * np.log(attr_norm + 1e-10))
    max_entropy = np.log(INPUT_LEN)
    return float(1.0 - (entropy / max_entropy))


def _run_lime_once(x, cls_idx):
    params    = CLASS_PARAMS[cls_idx]
    explainer = CLASS_EXPLAINERS[cls_idx]
    pf        = params["pf"]
    n_samples = params["n_samples"]

    exp = explainer.explain_instance(
        x.astype(np.float32),
        pf,
        num_features = INPUT_LEN,
        num_samples  = n_samples,
        top_labels   = 5
    )

    with torch.no_grad():
        raw_logits = _lime_model(
            torch.tensor(x[np.newaxis], dtype=torch.float32).to(device)
        )
    pc = int(raw_logits.argmax(dim=1).cpu().numpy()[0])

    if pc not in exp.local_exp:
        pc = list(exp.local_exp.keys())[0] if exp.local_exp else cls_idx

    if pc not in exp.local_exp:
        return np.zeros(INPUT_LEN), pc

    attr = np.zeros(INPUT_LEN)
    for feat_idx, weight in exp.local_exp[pc]:
        if 0 <= feat_idx < INPUT_LEN:
            attr[feat_idx] = weight
    return attr, pc


def _score_from_attr(attr, qrs):
    total = np.abs(attr).sum() + 1e-8
    return float(np.abs(attr[qrs[0]:qrs[1]]).sum() / total)


def _adaptive_trust(x: np.ndarray, cls_idx: int):
    """
    Compute LIME trust score. Runs LIME_RUNS times and averages attributions.
    Supraventricular: dynamic P-wave anchor with v5.5 guards.
    Unknown: entropy concentration penalty.
    """
    params = CLASS_PARAMS[cls_idx]
    qrs    = params["qrs"]
    diag   = {}

    if params.get("dynamic_anchor"):
        result = _dynamic_pwave_anchor(x)
        qrs    = (result[0], result[1])
        diag["dynamic_anchor"]        = qrs
        diag["dynamic_anchor_method"] = result[2]

    attrs = []
    pc    = cls_idx
    for _ in range(LIME_RUNS):
        attr_i, pc_i = _run_lime_once(x, cls_idx)
        attrs.append(attr_i)
        pc = pc_i

    attr  = np.mean(attrs, axis=0)
    score = _score_from_attr(attr, qrs)

    if cls_idx == 4:
        concentration         = _entropy_concentration(attr)
        diag["raw_score"]     = score
        diag["concentration"] = concentration
        score = max(score * concentration, 0.05)

    return score, attr, pc, {
        "T":         params["T"],
        "kw":        params["kw"],
        "n_samples": params["n_samples"],
        "qrs":       qrs,
    }, diag

# =============================================================================
# STEP 6 -- Run batch (10 samples per class = 50 total)
# =============================================================================
print("\n" + "="*62)
print(f"  ADAPTIVE LIME BATCH (10 samples/class, {LIME_RUNS}x averaged)")
print("="*62)

N_PER_CLASS = 10
all_scores, all_attrs, all_preds      = [], [], []
all_cls, all_params_used, all_diags   = [], [], []
unknown_raw_scores, unknown_concs     = [], []

t0_total = time.time()

for cls_idx, cfg in CLASS_CFG.items():
    cls_mask    = (_pred_classes == cls_idx)
    cls_indices = np.where(cls_mask)[0]

    if len(cls_indices) == 0:
        print(f"  {cfg['name']:<18}: SKIP -- no test samples predicted as this class")
        continue

    n_run  = min(N_PER_CLASS, len(cls_indices))
    rng_lime = np.random.default_rng(42 + cls_idx * 100)
    chosen = rng_lime.choice(cls_indices, n_run, replace=False)

    # FIX #4: for the dynamic-anchor class, don't print a single static qrs
    # header -- it's never actually applied uniformly at scoring time.
    _qrs_hdr = ("dynamic per-sample (static fallback=(20,110))"
                if CLASS_PARAMS[cls_idx].get("dynamic_anchor")
                else str(CLASS_PARAMS[cls_idx]['qrs']))
    print(f"\n  {cfg['name']} (T={CLASS_PARAMS[cls_idx]['T']:.1f}  "
          f"kw={CLASS_PARAMS[cls_idx]['kw']:.2f}  "
          f"n_samples={CLASS_PARAMS[cls_idx]['n_samples']}  "
          f"qrs={_qrs_hdr})  ->  running {n_run} samples")

    cls_scores = []
    t0_cls     = time.time()

    for test_idx in chosen:
        score, attr, pc, p_used, diag = _adaptive_trust(_X_test_all[test_idx], cls_idx)
        cls_scores.append(score)
        all_scores.append(score)
        all_attrs.append(attr)
        all_preds.append(pc)
        all_cls.append(cls_idx)
        all_params_used.append(p_used)
        all_diags.append(diag)

        if cls_idx == 4 and diag.get("raw_score") is not None:
            unknown_raw_scores.append(diag["raw_score"])
            unknown_concs.append(diag["concentration"])

    elapsed_cls = time.time() - t0_cls
    print(f"    mean={np.mean(cls_scores):.4f}  "
          f"std={np.std(cls_scores):.4f}  "
          f"min={np.min(cls_scores):.4f}  "
          f"max={np.max(cls_scores):.4f}  "
          f"time={elapsed_cls:.0f}s")

    if cls_idx == 1:
        supra_diags = all_diags[-n_run:]
        anchors     = [d.get("dynamic_anchor", CLASS_PARAMS[1]["qrs"])
                       for d in supra_diags]
        methods     = [d.get("dynamic_anchor_method", "fallback")
                       for d in supra_diags]
        n_dynamic   = sum(1 for m in methods if m == "dynamic")
        n_fallback  = sum(1 for m in methods if m == "fallback")
        widths      = [a[1]-a[0] for a in anchors]
        print(f"    [Supra dynamic anchor]  "
              f"dynamic={n_dynamic}  fallback={n_fallback}  "
              f"mean_width={np.mean(widths):.1f}  "
              f"anchor_range=({min(a[0] for a in anchors)},{max(a[1] for a in anchors)})")

    if cls_idx == 4 and unknown_raw_scores:
        print(f"    [Unknown entropy penalty]  "
              f"raw_score={np.mean(unknown_raw_scores):.4f}  "
              f"concentration={np.mean(unknown_concs):.4f}  "
              f"penalised={np.mean(cls_scores):.4f}")

# =============================================================================
# STEP 7 -- Results summary
# =============================================================================
all_scores = np.array(all_scores)
all_cls    = np.array(all_cls)
elapsed_tot= time.time() - t0_total

def _t_ci(scores, confidence=0.95):
    if len(scores) < 2:
        m = float(np.mean(scores)); return (m, m)
    lo, hi = scipy_stats.t.interval(
        confidence, df=len(scores)-1,
        loc=np.mean(scores), scale=scipy_stats.sem(scores)
    )
    return float(lo), float(hi)

def _verdict(mean_val):
    if mean_val >= 0.40: return "VALID (>=0.40)"
    if mean_val >= 0.28: return "REVIEW (>=0.28)"
    return "FAIL (<0.28)"

t1_scores = all_scores;                         t1_ci = _t_ci(t1_scores)
t2_mask   = (all_cls != 4); t2_scores = all_scores[t2_mask]; t2_ci = _t_ci(t2_scores)
t3_mask   = np.isin(all_cls,[0,1,2]); t3_scores = all_scores[t3_mask]; t3_ci = _t_ci(t3_scores)
unk_mask  = (all_cls == 4); unk_scores = all_scores[unk_mask]
unk_ci    = _t_ci(unk_scores) if unk_mask.sum() > 1 else (0.0, 0.0)

print(f"\n{'='*62}")
print(f"  LIME-1D v5.5 ADAPTIVE -- FINAL RESULTS")
print(f"  [Thresholds: VALID>=0.40  REVIEW>=0.28  FAIL<0.28]")
print(f"  [CI: 95% t-interval  |  T_MAX={T_MAX}  |  LIME_RUNS={LIME_RUNS}]")
print(f"{'='*62}")
print(f"  Tier 1  All classes      mean={t1_scores.mean():.4f}  "
      f"std={t1_scores.std():.4f}  "
      f"CI=[{t1_ci[0]:.4f},{t1_ci[1]:.4f}]  {_verdict(t1_scores.mean())}")
print(f"  Tier 2  Excl. Unknown    mean={t2_scores.mean():.4f}  "
      f"std={t2_scores.std():.4f}  "
      f"CI=[{t2_ci[0]:.4f},{t2_ci[1]:.4f}]  {_verdict(t2_scores.mean())}")
print(f"  Tier 3  Clinical only    mean={t3_scores.mean():.4f}  "
      f"std={t3_scores.std():.4f}  "
      f"CI=[{t3_ci[0]:.4f},{t3_ci[1]:.4f}]  {_verdict(t3_scores.mean())}")
print(f"  Unknown (diagnostic)     mean={unk_scores.mean():.4f}  "
      f"std={unk_scores.std():.4f}  "
      f"CI=[{unk_ci[0]:.4f},{unk_ci[1]:.4f}]  [excluded from all tiers]"
      if unk_mask.sum() > 0 else "  Unknown: no samples")
print(f"  Total time = {elapsed_tot:.0f}s")

print(f"\n  Per-class breakdown:")
print(f"  {'Class':<18} {'mean':>6}  {'std':>6}  {'min':>6}  {'max':>6}  "
      f"{'n':>4}  {'T':>5}  {'CI_lo':>6}  {'CI_hi':>6}  {'QRS anchor':<22}  Verdict")
print("  " + "-"*116)
for c, cfg in CLASS_CFG.items():
    m = (all_cls == c)
    if m.sum() > 0:
        sc   = all_scores[m]
        ci   = _t_ci(sc)
        pu   = all_params_used[np.where(m)[0][0]]

        # FIX #4: report the actual per-sample anchor range for the
        # dynamic-anchor class instead of a single static config value
        # that was never applied uniformly.
        if cfg.get("dynamic_anchor"):
            _anchors_c = [all_params_used[i]["qrs"] for i in np.where(m)[0]]
            _qrs_disp  = f"varies({min(a[0] for a in _anchors_c)}-{max(a[1] for a in _anchors_c)})"
        else:
            _qrs_disp = str(pu['qrs'])

        verd = "VALID" if sc.mean()>=0.40 else "REVIEW" if sc.mean()>=0.28 else "FAIL"
        note = "  [diagnostic only]" if c == 4 else ""
        if m.sum() < 5:
            note += "  [LOW N -- CI not meaningful]"
        print(f"  {cfg['name']:<18} {sc.mean():6.4f}  {sc.std():6.4f}  "
              f"{sc.min():6.4f}  {sc.max():6.4f}  {m.sum():4d}  "
              f"{pu['T']:5.1f}  {ci[0]:6.4f}  {ci[1]:6.4f}  "
              f"{_qrs_disp:<22}  {verd}{note}")
    else:
        print(f"  {cfg['name']:<18} {'--':>6}  {'--':>6}  {'--':>6}  {'--':>6}  "
              f"{'0':>4}  {'--':>5}  {'--':>6}  {'--':>6}  --")

lime_1d_scores_fixed = all_scores
try:
    for s in all_scores: xai_report.add_lime_1d_result(float(s))
    print("\n  [OK] Scores added to xai_report")
except (NameError, AttributeError):
    print("\n  [INFO] Stored in lime_1d_scores_fixed")

# =============================================================================
# STEP 8 -- FIGURES
# =============================================================================
BG="#0d1117"; PAN="#161b22"; GRID="#30363d"; TX="#c9d1d9"; TX2="#8b949e"
BLUE="#58a6ff"; GREEN="#2ea44f"; RED="#e5534b"; PURP="#534AB7"; GOLD="#d29922"
ORANGE="#f0883e"
CLS_COLS = [BLUE, GREEN, RED, PURP, GOLD]

cls_names_list = [CLASS_CFG[c]["name"] for c in range(5)]
cls_means_new, cls_stds_new, cls_ns, cls_cis = [], [], [], []
for c in range(5):
    m = (all_cls == c)
    cls_means_new.append(all_scores[m].mean() if m.sum() > 0 else 0)
    cls_stds_new.append(all_scores[m].std()   if m.sum() > 0 else 0)
    cls_ns.append(int(m.sum()))
    # FIX #2: was `_t_ci(...) if m.sum() > 1 else (0, 0)` -- the (0,0) fallback
    # for n==1 could be LESS than a nonzero mean, producing a negative yerr
    # below. _t_ci() already returns (mean, mean) correctly for n<2, so just
    # always call it whenever there's at least one sample.
    cls_cis.append(_t_ci(all_scores[m]) if m.sum() > 0 else (0, 0))

cls_means_v54 = [0.4510, 0.2422, 0.4225, 0.4241, 0.0824]

# -- FIG 1: Bar comparison -----------------------------------------------------
fig1, axes1 = plt.subplots(1, 2, figsize=(18, 6), facecolor=BG)
fig1.suptitle(
    "LIME-1D v5.5 -- Fixes: T_MAX cap - target_min=0.65 - "
    "P-wave amplitude guard - anchor min-width - edge exclusion\n"
    "Thresholds calibrated for 1D tabular LIME on 187-pt ECG signals",
    color=TX, fontsize=12, fontweight="bold")

for ax in axes1:
    ax.set_facecolor(PAN)
    for sp in ax.spines.values(): sp.set_color(GRID)
    ax.tick_params(colors=TX2)
    ax.grid(color=GRID, lw=0.4, alpha=0.5, axis="y")

x = np.arange(5); w = 0.35
axes1[0].bar(x - w/2, cls_means_v54, w, color="#484f58",
             label="v5.4 (previous)", alpha=0.7, zorder=3)
b2 = axes1[0].bar(x + w/2, cls_means_new, w, color=CLS_COLS,
                  label="v5.5 (current)", zorder=3,
                  yerr=cls_stds_new, capsize=5,
                  error_kw={"color": TX, "lw": 1.5})
for bar, val, std, n, c in zip(b2, cls_means_new, cls_stds_new, cls_ns, range(5)):
    if val > 0:
        suffix = "\ndiag" if c == 4 else ""
        axes1[0].text(bar.get_x()+bar.get_width()/2, val + std + 0.03,
                      f"{val:.3f}\n(n={n}){suffix}",
                      ha="center", color=TX, fontsize=8, fontweight="bold")

for i, (mean, ci) in enumerate(zip(cls_means_new, cls_cis)):
    if mean > 0:
        axes1[0].errorbar(x[i] + w/2, mean,
                          yerr=[[mean - ci[0]], [ci[1] - mean]],
                          fmt="none", color=ORANGE, lw=2, capsize=7,
                          label="95% t-CI" if i == 0 else "")

axes1[0].axhline(0.28, color=GOLD,   ls=":",  lw=1.5, label="0.28 REVIEW")
axes1[0].axhline(0.40, color=GREEN,  ls="--", lw=2,   label="0.40 VALID")
axes1[0].axhline(t2_scores.mean(), color=BLUE,   ls="-.", lw=1.5,
                 label=f"T2 mean={t2_scores.mean():.3f}")
axes1[0].axhline(t3_scores.mean(), color=ORANGE, ls="-.", lw=1.5,
                 label=f"T3 mean={t3_scores.mean():.3f}")
axes1[0].set_xticks(x); axes1[0].set_xticklabels(cls_names_list, color=TX2, fontsize=10)
axes1[0].set_ylabel("Mean LIME-1D Trust Score", color=TX2)
axes1[0].set_ylim(0, 1.0)
axes1[0].set_title("v5.4 vs v5.5 Trust Scores", color=TX, fontsize=11, fontweight="bold")
axes1[0].legend(facecolor=PAN, labelcolor=TX, fontsize=8)

param_labels = ["T (capped)", "Kernel width", "n_samples", "QRS anchor", "Avg runs"]
table_data   = []
for c in range(5):
    p   = CLASS_PARAMS[c]
    dyn = "dynamic" if p.get("dynamic_anchor") else f"{p['qrs'][0]}-{p['qrs'][1]}"
    table_data.append([
        f"{p['T']:.1f}" + ("*" if p['T'] >= T_MAX - 0.01 else ""),
        f"{p['kw']:.2f}",
        f"{p['n_samples']:,}",
        dyn,
        str(LIME_RUNS)
    ])

axes1[1].axis("off")
tbl = axes1[1].table(cellText=table_data, rowLabels=cls_names_list,
                     colLabels=param_labels, cellLoc="center", loc="center")
tbl.auto_set_font_size(False); tbl.set_fontsize(10); tbl.scale(1.2, 2.2)
for (r, c_), cell in tbl.get_celld().items():
    cell.set_facecolor(PAN if r > 0 else "#1f2937")
    cell.set_text_props(color=TX if r > 0 else GOLD)
    cell.set_edgecolor(GRID)
    if r > 0 and c_ == -1:
        cell.set_text_props(color=CLS_COLS[r-1], fontsize=11, fontweight="bold")
axes1[1].set_title("Class-Specific Parameters (v5.5)", color=TX,
                   fontsize=11, fontweight="bold", pad=20)

plt.tight_layout()
_p1 = f"{output_dir}/lime_1d_v55_comparison.png"
plt.savefig(_p1, dpi=300, bbox_inches="tight", facecolor=BG); plt.close()
print(f"\n  [FIG 1] {_p1}")

# -- FIG 2: 5-class attribution grid -------------------------------------------
fig2, axes2 = plt.subplots(5, 1, figsize=(18, 22), facecolor=BG)
fig2.suptitle(
    "LIME-1D v5.5 Averaged Attributions -- Best Sample Per Arrhythmia Class\n"
    f"3x averaging - dynamic P-wave (amplitude guard) - T_MAX={T_MAX} - "
    "Unknown: diagnostic only",
    color=TX, fontsize=13, fontweight="bold", y=1.005)

for cls_idx in range(5):
    ax  = axes2[cls_idx]
    cfg = CLASS_CFG[cls_idx]
    ax.set_facecolor(PAN); ax.tick_params(colors=TX2)
    ax.grid(color=GRID, lw=0.4, alpha=0.4, axis="y")
    for sp in ax.spines.values(): sp.set_color(GRID)

    m = (all_cls == cls_idx)
    if m.sum() == 0:
        ax.text(93, 0, f"No samples predicted as {cfg['name']}", ha="center",
                color=TX2, fontsize=12)
        ax.set_ylabel(cfg["name"], color=CLS_COLS[cls_idx], fontsize=11, fontweight="bold")
        continue

    idxs       = np.where(m)[0]
    best_local = int(np.argmax(all_scores[m]))
    best_i     = idxs[best_local]
    attr       = np.array(all_attrs[best_i])
    orig_idx   = np.where(_pred_classes == cls_idx)[0][best_local]
    x_sig      = _X_test_all[orig_idx]
    x_n        = (x_sig - x_sig.mean()) / (x_sig.std() + 1e-8) * 0.25
    p_used     = all_params_used[best_i]
    qrs        = p_used["qrs"]
    score      = all_scores[best_i]
    diag       = all_diags[best_i]

    ax.fill_between(range(INPUT_LEN), x_n, alpha=0.18, color=CLS_COLS[cls_idx],
                    label="ECG signal (norm x0.25)")
    ax.bar(range(INPUT_LEN), np.where(attr > 0, attr, 0),
           color=GREEN, alpha=0.85, width=1.0, label="+weight")
    ax.bar(range(INPUT_LEN), np.where(attr < 0, attr, 0),
           color=RED,   alpha=0.85, width=1.0, label="-weight")

    anchor_lbl = f"QRS anchor ({qrs[0]}-{qrs[1]})"
    if diag.get("dynamic_anchor_method") == "dynamic":
        anchor_lbl += " dynamic"
    elif diag.get("dynamic_anchor_method") == "fallback":
        anchor_lbl += " [fallback]"
    ax.axvspan(qrs[0], qrs[1], color=CLS_COLS[cls_idx], alpha=0.10, label=anchor_lbl)
    if qrs != (60, 125):
        ax.axvspan(60, 125, color="#484f58", alpha=0.06, label="Normal QRS ref")

    peak_t  = int(np.argmax(np.abs(attr)))
    qrs_pct = np.abs(attr[qrs[0]:qrs[1]]).sum() / (np.abs(attr).sum() + 1e-8)
    in_qrs  = "IN anchor" if qrs[0] <= peak_t <= qrs[1] else "outside"
    if np.abs(attr).max() > 1e-6:
        ax.axvline(peak_t, color=GOLD, ls=":", lw=1.5, alpha=0.9)

    extra = ""
    if cls_idx == 4 and diag.get("raw_score") is not None:
        extra = (f"  |  raw={diag['raw_score']:.4f}  "
                 f"conc={diag['concentration']:.4f}  penalised={score:.4f}  [diag]")
    elif cls_idx == 1:
        meth  = diag.get("dynamic_anchor_method", "?")
        extra = f"  |  anchor_method={meth}  anchor={diag.get('dynamic_anchor','static')}"

    ax.set_ylabel(cfg["name"], color=CLS_COLS[cls_idx], fontsize=11, fontweight="bold")
    ax.set_title(
        f"{cfg['name']}  |  trust={score:.4f}  (n={m.sum()})  |  "
        f"anchor_attr={qrs_pct:.3f}  |  peak t={peak_t}  {in_qrs}{extra}\n"
        f"T={p_used['T']:.1f}  kw={p_used['kw']:.2f}  "
        f"n_samples={p_used['n_samples']}  runs={LIME_RUNS}  -- {cfg['note']}",
        color=TX, fontsize=9, pad=3)
    if cls_idx == 0:
        ax.legend(facecolor=PAN, labelcolor=TX, fontsize=8, loc="upper right", ncol=5)
    if cls_idx == 4:
        ax.set_xlabel("Time step (0-186)", color=TX2, fontsize=11)

plt.tight_layout()
_p2 = f"{output_dir}/lime_1d_v55_5class.png"
plt.savefig(_p2, dpi=300, bbox_inches="tight", facecolor=BG); plt.close()
print(f"  [FIG 2] {_p2}")

# -- FIG 3: Distribution + tier summary + per-class CI -------------------------
fig3, axes3 = plt.subplots(1, 3, figsize=(22, 6), facecolor=BG)
for ax in axes3:
    ax.set_facecolor(PAN)
    for sp in ax.spines.values(): sp.set_color(GRID)
    ax.tick_params(colors=TX2)
    ax.grid(color=GRID, lw=0.4, alpha=0.5)

for c in range(5):
    m = (all_cls == c)
    if m.sum() > 1:
        axes3[0].hist(all_scores[m], bins=8, color=CLS_COLS[c], alpha=0.55,
                      label=CLASS_CFG[c]["name"] + (" *" if c == 4 else ""), zorder=3)
axes3[0].axvline(t1_scores.mean(), color=GOLD,   ls="--", lw=2,
                 label=f"T1={t1_scores.mean():.4f}")
axes3[0].axvline(t2_scores.mean(), color=BLUE,   ls="-.", lw=2,
                 label=f"T2={t2_scores.mean():.4f}")
axes3[0].axvline(t3_scores.mean(), color=ORANGE, ls="-.", lw=2,
                 label=f"T3={t3_scores.mean():.4f}")
axes3[0].axvline(0.28, color=GOLD,  ls=":", lw=1.2, alpha=0.7)
axes3[0].axvline(0.40, color=GREEN, ls=":", lw=1.2, alpha=0.7)
axes3[0].set_xlabel("LIME-1D Trust Score", color=TX2, fontsize=11)
axes3[0].set_ylabel("Count", color=TX2)
axes3[0].set_title("Score Distribution by Class", color=TX, fontsize=11, fontweight="bold")
axes3[0].legend(facecolor=PAN, labelcolor=TX, fontsize=8)

tier_means = [t1_scores.mean(), t2_scores.mean(), t3_scores.mean()]
tier_stds  = [t1_scores.std(),  t2_scores.std(),  t3_scores.std()]
tier_cis   = [t1_ci,            t2_ci,             t3_ci]
bars = axes3[1].bar(range(3), tier_means, color=[GOLD, BLUE, ORANGE], alpha=0.85,
                    zorder=3, yerr=tier_stds, capsize=6,
                    error_kw={"color": TX, "lw": 1.5})
for i, (bar, mean, std, ci) in enumerate(zip(bars, tier_means, tier_stds, tier_cis)):
    verd = "VALID" if mean >= 0.40 else "REVIEW" if mean >= 0.28 else "FAIL"
    axes3[1].text(bar.get_x()+bar.get_width()/2, mean + std + 0.03,
                  f"{mean:.4f}\n{verd}\nCI[{ci[0]:.3f},{ci[1]:.3f}]",
                  ha="center", color=TX, fontsize=9, fontweight="bold")
axes3[1].axhline(0.28, color=GOLD,  ls=":",  lw=1.5, label="0.28 REVIEW")
axes3[1].axhline(0.40, color=GREEN, ls="--", lw=2,   label="0.40 VALID")
axes3[1].set_xticks(range(3))
axes3[1].set_xticklabels(["All\n(T1)", "Excl Unk\n(T2)", "Clinical\n(T3)"],
                          color=TX2, fontsize=10)
axes3[1].set_ylabel("Mean Trust Score", color=TX2); axes3[1].set_ylim(0, 0.90)
axes3[1].set_title("Three-Tier Aggregate  |  95% t-CI", color=TX,
                   fontsize=11, fontweight="bold")
axes3[1].legend(facecolor=PAN, labelcolor=TX, fontsize=9)

x_cls = np.arange(5)
bars3 = axes3[2].bar(x_cls, cls_means_new, color=CLS_COLS, alpha=0.80, zorder=3,
                     yerr=cls_stds_new, capsize=5, error_kw={"color": TX, "lw": 1.5})
for i, (mean, ci) in enumerate(zip(cls_means_new, cls_cis)):
    if mean > 0:
        axes3[2].errorbar(x_cls[i], mean,
                          yerr=[[mean - ci[0]], [ci[1] - mean]],
                          fmt="none", color=ORANGE, lw=2.5, capsize=8)
for bar, val, std, n in zip(bars3, cls_means_new, cls_stds_new, cls_ns):
    if val > 0:
        axes3[2].text(bar.get_x()+bar.get_width()/2, val + std + 0.04,
                      f"{val:.3f}\nn={n}", ha="center", color=TX,
                      fontsize=8, fontweight="bold")
axes3[2].axhline(0.28, color=GOLD,  ls=":",  lw=1.5)
axes3[2].axhline(0.40, color=GREEN, ls="--", lw=2)
axes3[2].set_xticks(x_cls)
axes3[2].set_xticklabels(cls_names_list, color=TX2, fontsize=9)
axes3[2].set_ylabel("Mean Trust Score", color=TX2); axes3[2].set_ylim(0, 0.90)
axes3[2].set_title("Per-Class Scores + 95% t-CI", color=TX,
                   fontsize=11, fontweight="bold")

plt.tight_layout()
_p3 = f"{output_dir}/lime_1d_v55_summary.png"
plt.savefig(_p3, dpi=300, bbox_inches="tight", facecolor=BG); plt.close()
print(f"  [FIG 3] {_p3}")

print(f"""
LIME-1D v5.5 ADAPTIVE complete -- 3 figures at 300 DPI
   {_p1}
   {_p2}
   {_p3}

   -- Three-Tier Results (VALID>=0.40 / REVIEW>=0.28 / FAIL<0.28 | 95% t-CI) --
   Tier 1  All classes    : {t1_scores.mean():.4f} +/- {t1_scores.std():.4f}  CI=[{t1_ci[0]:.4f},{t1_ci[1]:.4f}]  {_verdict(t1_scores.mean())}
   Tier 2  Excl Unknown   : {t2_scores.mean():.4f} +/- {t2_scores.std():.4f}  CI=[{t2_ci[0]:.4f},{t2_ci[1]:.4f}]  {_verdict(t2_scores.mean())}
   Tier 3  Clinical only  : {t3_scores.mean():.4f} +/- {t3_scores.std():.4f}  CI=[{t3_ci[0]:.4f},{t3_ci[1]:.4f}]  {_verdict(t3_scores.mean())}
   Unknown (diagnostic)   : {unk_scores.mean():.4f} +/- {unk_scores.std():.4f}  CI=[{unk_ci[0]:.4f},{unk_ci[1]:.4f}]  [excl. all tiers]

   -- Per-class -----------------------------------------------------------""")
for c in range(5):
    m = (all_cls == c)
    if m.sum() > 0:
        sc = all_scores[m]; ci = _t_ci(sc)
        vd = "VALID" if sc.mean()>=0.40 else "REVIEW" if sc.mean()>=0.28 else "FAIL"
        note = "  [diagnostic only]" if c == 4 else ""
        if m.sum() < 5:
            note += "  [LOW N]"
        print(f"   {CLASS_CFG[c]['name']:<18}: {sc.mean():.4f} +/- {sc.std():.4f}  "
              f"CI=[{ci[0]:.4f},{ci[1]:.4f}]  {vd}{note}")

# =============================================================================
# OVERALL QRS WINDOW (TIER 2) — CALCULATION & VISUALIZATION
# =============================================================================
# Run this AFTER Cell 24 (LIME-1D v5.5) completes
# Calculates: Tier 2 = All classes EXCEPT Unknown (diagnostic-only)
# This is your primary "Overall" metric for publication
# =============================================================================

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy import stats as scipy_stats

# Verify prerequisites
try:
    _ = all_scores
    _ = all_cls
    print(f'[OK] LIME-1D v5.5 results loaded')
    print(f'     all_scores: {len(all_scores)} samples')
    print(f'     all_cls: {len(all_cls)} labels')
except NameError:
    print('[FATAL] Run Cell 24 (LIME-1D v5.5) first'); raise

# =============================================================================
# TIER 2: OVERALL QRS (ALL CLASSES EXCEPT UNKNOWN)
# =============================================================================

all_scores_arr = np.array(all_scores)
all_cls_arr = np.array(all_cls)

# Filter: exclude Unknown class (cls_idx=4, diagnostic only)
tier2_mask = (all_cls_arr != 4)
tier2_scores = all_scores_arr[tier2_mask]

print('\n' + '='*70)
print('  TIER 2 — OVERALL QRS WINDOW (Fixed + Adaptive Anchors)')
print('  Includes: Normal, Supraventricular, PVC, Fusion')
print('  Excludes: Unknown (diagnostic-only)')
print('='*70)

# Calculate statistics
tier2_mean = float(tier2_scores.mean())
tier2_std = float(tier2_scores.std())
tier2_n = len(tier2_scores)
tier2_min = float(tier2_scores.min())
tier2_max = float(tier2_scores.max())
tier2_median = float(np.median(tier2_scores))

# Calculate 95% t-confidence interval
if len(tier2_scores) < 2:
    tier2_ci = (tier2_mean, tier2_mean)
else:
    lo, hi = scipy_stats.t.interval(
        0.95, df=len(tier2_scores)-1,
        loc=np.mean(tier2_scores), scale=scipy_stats.sem(tier2_scores)
    )
    tier2_ci = (float(lo), float(hi))

# Verdict
def _verdict(mean_val):
    if mean_val >= 0.40: return "VALID (≥0.40)"
    if mean_val >= 0.28: return "REVIEW (≥0.28)"
    return "FAIL (<0.28)"

verdict_t2 = _verdict(tier2_mean)

print(f'\n  Primary Metric (OVERALL QRS):')
print(f'  ─' * 70)
print(f'  Mean:           {tier2_mean:.4f}')
print(f'  Std Dev:        {tier2_std:.4f}')
print(f'  95% t-CI:       [{tier2_ci[0]:.4f}, {tier2_ci[1]:.4f}]')
print(f'  Median:         {tier2_median:.4f}')
print(f'  Min / Max:      {tier2_min:.4f} / {tier2_max:.4f}')
print(f'  N (samples):    {tier2_n}')
print(f'  Verdict:        {verdict_t2}')
print(f'  ─' * 70)

# Per-class breakdown within Tier 2
print(f'\n  Per-Class Breakdown (Tier 2 only):')
print(f'  ─' * 70)
class_names = ['Normal', 'Supraventricular', 'PVC', 'Fusion']
for cls_idx in range(4):  # Only 0-3, exclude 4 (Unknown)
    mask = (all_cls_arr == cls_idx)
    if mask.sum() > 0:
        cls_scores = all_scores_arr[mask]
        cls_mean = cls_scores.mean()
        cls_std = cls_scores.std()
        cls_n = len(cls_scores)

        if cls_n < 2:
            cls_ci = (cls_mean, cls_mean)
        else:
            lo, hi = scipy_stats.t.interval(
                0.95, df=cls_n-1,
                loc=cls_mean, scale=scipy_stats.sem(cls_scores)
            )
            cls_ci = (float(lo), float(hi))

        cls_verdict = _verdict(cls_mean)
        print(f'  {class_names[cls_idx]:<18}: '
              f'mean={cls_mean:.4f}  std={cls_std:.4f}  '
              f'CI=[{cls_ci[0]:.4f},{cls_ci[1]:.4f}]  '
              f'n={cls_n}  {cls_verdict}')

print(f'  ─' * 70)

# =============================================================================
# PUBLICATION-READY FIGURE: TIER 2 OVERALL QRS
# =============================================================================

output_dir = './ecg_results_figures'
BG = "#0d1117"
PAN = "#161b22"
GRID = "#30363d"
TX = "#c9d1d9"
TX2 = "#8b949e"
GREEN = "#2ea44f"
GOLD = "#d29922"
BLUE = "#58a6ff"
ORANGE = "#f0883e"

fig, ax = plt.subplots(1, 1, figsize=(12, 7), facecolor=BG)
ax.set_facecolor(PAN)
for sp in ax.spines.values():
    sp.set_color(GRID)
ax.tick_params(colors=TX2)
ax.grid(color=GRID, lw=0.5, alpha=0.4, axis='y')

# Large histogram
n, bins, patches = ax.hist(tier2_scores, bins=15, color=BLUE, alpha=0.75,
                           edgecolor=TX, linewidth=1.2, zorder=3)

# Add mean line
ax.axvline(tier2_mean, color=GREEN, linestyle='--', linewidth=2.5,
           label=f'Mean = {tier2_mean:.4f}')

# Add median line
ax.axvline(tier2_median, color=ORANGE, linestyle='-.', linewidth=2,
           label=f'Median = {tier2_median:.4f}')

# Add CI bounds
ax.axvline(tier2_ci[0], color=GOLD, linestyle=':', linewidth=2, alpha=0.8)
ax.axvline(tier2_ci[1], color=GOLD, linestyle=':', linewidth=2, alpha=0.8,
           label=f'95% CI = [{tier2_ci[0]:.4f}, {tier2_ci[1]:.4f}]')

# Add VALID/REVIEW/FAIL thresholds
ax.axvline(0.28, color='#d4a574', linestyle='--', linewidth=1.5, alpha=0.5)
ax.axvline(0.40, color=GREEN, linestyle='--', linewidth=1.5, alpha=0.5)
ax.text(0.28, ax.get_ylim()[1]*0.95, '0.28\nREVIEW', ha='center',
        fontsize=9, color='#d4a574', fontweight='bold')
ax.text(0.40, ax.get_ylim()[1]*0.95, '0.40\nVALID', ha='center',
        fontsize=9, color=GREEN, fontweight='bold')

# Shaded regions
ax.axvspan(0.0, 0.28, alpha=0.05, color='red', label='FAIL region')
ax.axvspan(0.28, 0.40, alpha=0.05, color='yellow', label='REVIEW region')
ax.axvspan(0.40, 1.0, alpha=0.05, color='green', label='VALID region')

ax.set_xlabel('LIME-1D Trust Score', fontsize=12, color=TX2, fontweight='bold')
ax.set_ylabel('Count (samples)', fontsize=12, color=TX2, fontweight='bold')
ax.set_xlim(0, 1.0)
ax.set_title(
    f'Overall QRS Window (Tier 2) — LIME-1D v5.5\n'
    f'Mean = {tier2_mean:.4f} ± {tier2_std:.4f}  |  N = {tier2_n}  |  '
    f'Verdict: {verdict_t2}',
    fontsize=13, color=TX, fontweight='bold', pad=15
)
ax.legend(facecolor=PAN, labelcolor=TX, fontsize=10, loc='upper left',
          framealpha=0.95)

# Add summary box
summary_text = (
    f'Tier 2: Overall QRS Window\n'
    f'━━━━━━━━━━━━━━━━━━━━━━━━━━━\n'
    f'Mean:  {tier2_mean:.4f}\n'
    f'Std:   {tier2_std:.4f}\n'
    f'95% CI: [{tier2_ci[0]:.4f}, {tier2_ci[1]:.4f}]\n'
    f'Min/Max: {tier2_min:.4f} / {tier2_max:.4f}\n'
    f'N: {tier2_n} samples\n'
    f'Verdict: {verdict_t2}'
)
props = dict(boxstyle='round', facecolor=PAN, alpha=0.95, edgecolor=GRID, linewidth=2)
ax.text(0.98, 0.65, summary_text, transform=ax.transAxes, fontsize=11,
        verticalalignment='top', horizontalalignment='right',
        fontfamily='monospace', bbox=props, color=TX)

plt.tight_layout()
fig_path = f'{output_dir}/tier2_overall_qrs_window.png'
plt.savefig(fig_path, dpi=300, bbox_inches='tight', facecolor=BG)
plt.close()
print(f'\n[FIG] Saved: {fig_path}')

# =============================================================================
# EXPORT RESULTS AS JSON
# =============================================================================

import json

tier2_results = {
    'name': 'Tier 2 — Overall QRS Window (Fixed + Adaptive Anchors)',
    'description': 'All clinical ECG classes (Normal, Supraventricular, PVC, Fusion). Excludes Unknown (diagnostic-only).',
    'method': 'LIME-1D v5.5 with class-specific temperature tuning and adaptive P-wave anchor',
    'statistics': {
        'mean': float(tier2_mean),
        'std': float(tier2_std),
        'median': float(tier2_median),
        'min': float(tier2_min),
        'max': float(tier2_max),
        'n_samples': int(tier2_n),
        'ci_95': [float(tier2_ci[0]), float(tier2_ci[1])],
        'verdict': verdict_t2
    },
    'thresholds': {
        'valid': {'min': 0.40, 'label': 'VALID'},
        'review': {'min': 0.28, 'max': 0.40, 'label': 'REVIEW'},
        'fail': {'max': 0.28, 'label': 'FAIL'}
    },
    'per_class': {}
}

for cls_idx in range(4):
    mask = (all_cls_arr == cls_idx)
    if mask.sum() > 0:
        cls_scores = all_scores_arr[mask]
        cls_mean = cls_scores.mean()
        cls_std = cls_scores.std()
        cls_n = len(cls_scores)

        if cls_n < 2:
            cls_ci = (cls_mean, cls_mean)
        else:
            lo, hi = scipy_stats.t.interval(
                0.95, df=cls_n-1,
                loc=cls_mean, scale=scipy_stats.sem(cls_scores)
            )
            cls_ci = (float(lo), float(hi))

        cls_verdict = _verdict(cls_mean)
        tier2_results['per_class'][class_names[cls_idx]] = {
            'mean': float(cls_mean),
            'std': float(cls_std),
            'n': int(cls_n),
            'ci_95': list(cls_ci),
            'verdict': cls_verdict
        }

json_path = f'{output_dir}/tier2_overall_qrs_results.json'
with open(json_path, 'w') as f:
    json.dump(tier2_results, f, indent=2)
print(f'[JSON] Saved: {json_path}')

# =============================================================================
# SUMMARY FOR PAPER
# =============================================================================

print('\n' + '='*70)
print('  READY FOR PUBLICATION')
print('='*70)
print(f'''
CITE THIS IN YOUR PAPER:
────────────────────────────────────────────────────────────────

Overall LIME-1D Faithfulness (Tier 2):
  Mean trust score = {tier2_mean:.4f} ± {tier2_std:.4f}
  95% CI: [{tier2_ci[0]:.4f}, {tier2_ci[1]:.4f}]
  Verdict: {verdict_t2}

  This overall metric combines fixed QRS windows for Normal/PVC/Fusion
  with adaptive P-wave anchors for Supraventricular beats (n={tier2_n}
  samples across 4 clinical classes).

FIGURE: tier2_overall_qrs_window.png
JSON:   tier2_overall_qrs_results.json
''')
print('='*70)