# -*- coding: utf-8 -*-
"""External_Validation_incart_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ysuiRtOsJ8oQGT85ajwmR9QaRzMBuQfe
"""







!pip install -U wfdb shap==0.44.0 captum==0.6.0 lime==0.2.0.1 \
             scipy scikit-learn seaborn tqdm matplotlib --quiet

import numpy as np, pandas as pd, wfdb
print("numpy:", np.__version__, "| pandas:", pd.__version__, "| wfdb:", wfdb.__version__)

# FIX: mount Google Drive and save all checkpoints there instead of the local
# Colab VM disk. Local /content/ storage is wiped on a full runtime reset (not just
# an idle disconnect) — a timeout partway through this notebook used to mean losing
# every .pt checkpoint (mendeley_best.pt, multiscale_best.pt, ecgresnetse_best.pt)
# and having to retrain everything from scratch. Every torch.save/torch.load call
# below now goes through CHECKPOINT_DIR so checkpoints survive a runtime reset.
import os

try:
    from google.colab import drive
    drive.mount('/content/drive')
    CHECKPOINT_DIR = '/content/drive/MyDrive/ECG_Project_Checkpoints'
except (ImportError, ModuleNotFoundError):
    # not running in Colab (e.g. local Jupyter) — fall back to a local folder
    CHECKPOINT_DIR = os.path.join(os.getcwd(), 'ecg_checkpoints')

os.makedirs(CHECKPOINT_DIR, exist_ok=True)
print(f'[OK] Checkpoints will be saved to: {CHECKPOINT_DIR}')

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
from scipy.signal import resample
from collections import Counter
from sklearn.metrics import f1_score, classification_report, confusion_matrix, ConfusionMatrixDisplay
from sklearn.model_selection import train_test_split

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("GPU available:", torch.cuda.is_available(), "| device:", device)

output_dir = "/content"
os.makedirs(output_dir, exist_ok=True)

INCART_DIR = "/content/incart_data"
os.makedirs(INCART_DIR, exist_ok=True)
records_to_fetch = [f"I{i:02d}" for i in range(1, 76)]

AAMI_MAP = {
    'N': 0, 'L': 0, 'R': 0, 'e': 0, 'j': 0,
    'A': 1, 'a': 1, 'J': 1, 'S': 1,
    'V': 2, 'E': 2,
    'F': 3,
    '/': 4, 'f': 4, 'Q': 4,
}
CLASS_NAMES = {0: 'N', 1: 'S', 2: 'V', 3: 'F', 4: 'Q'}

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
from scipy.signal import resample
from collections import Counter
from sklearn.metrics import f1_score, classification_report, confusion_matrix, ConfusionMatrixDisplay
from sklearn.model_selection import train_test_split

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("GPU available:", torch.cuda.is_available(), "| device:", device)

from google.colab import drive
drive.mount('/content/drive')
CHECKPOINT_DIR = "/content/drive/MyDrive/ECG_Project_Checkpoints"
print(os.listdir(CHECKPOINT_DIR))

!mkdir -p ~/.kaggle
!cp /content/kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!kaggle datasets download -d shayanfazeli/heartbeat

import zipfile
os.makedirs('/content/data/kaggle', exist_ok=True)
with zipfile.ZipFile('heartbeat.zip', 'r') as z:
    z.extractall('/content/data/kaggle/')
os.remove('heartbeat.zip')
print(os.listdir('/content/data/kaggle/'))

wfdb.dl_database('incartdb', dl_dir=INCART_DIR)
print(len(os.listdir(INCART_DIR)), "files")



# =============================================================================
# STEP 0 — Verify INCART completeness; redownload if incomplete
# =============================================================================
import os, shutil

INCART_DIR = "/content/incart_data"

def check_incart_complete(d, expected_records=75):
    if not os.path.isdir(d):
        return False, [], 0
    files = os.listdir(d)
    hea_files = sorted({f.split('.')[0] for f in files if f.endswith('.hea')})
    missing = []
    for rec in hea_files:
        for ext in ('.hea', '.dat', '.atr'):
            if not os.path.exists(os.path.join(d, f"{rec}{ext}")):
                missing.append(f"{rec}{ext}")
    complete = (len(hea_files) == expected_records) and (len(missing) == 0)
    return complete, missing, len(hea_files)

complete, missing, n_records = check_incart_complete(INCART_DIR)
print(f"Records found: {n_records}/75   Missing files: {len(missing)}")
if missing:
    print("Missing:", missing[:20], "..." if len(missing) > 20 else "")

if not complete:
    print("\n[FIX] INCART incomplete — wiping and redownloading full dataset...")
    shutil.rmtree(INCART_DIR, ignore_errors=True)
    os.makedirs(INCART_DIR, exist_ok=True)
    import wfdb
    wfdb.dl_database('incartdb', dl_dir=INCART_DIR)
    complete, missing, n_records = check_incart_complete(INCART_DIR)
    print(f"\nAfter redownload — records: {n_records}/75   Missing: {len(missing)}")
    if not complete:
        raise RuntimeError(f"INCART still incomplete after redownload. Missing: {missing}")
    print("[OK] INCART complete.")
else:
    print("[OK] INCART already complete.")

import pandas as pd

# Define the exact path to your downloaded Kaggle dataset in Colab
file_path = '/content/data/kaggle/mitbih_train.csv'

try:
    # Read the dataset without headers
    df = pd.read_csv(file_path, header=None)

    print("=" * 45)
    print("Kaggle CSV Integrity Check")
    print("=" * 45)
    print('Shape:', df.shape)         # Verification Check: Must be (87554, 188)
    print('Classes:', df[187].value_counts().to_dict())
    print("-" * 45)
    print("[SUCCESS] Dataset matches expectations and is readable!")

except FileNotFoundError:
    print(f"[ERROR] Could not find the file at {file_path}.")
    print("Please verify your file structure in the left sidebar folder tree.")
except Exception as e:
    print(f"[ERROR] An unexpected error occurred: {e}")

# NOTE (leak-fix pass): this cell is the single source of truth for
# X_train/y_train/X_val/y_val used by every training cell below.
# Do NOT let any later cell reassign these from X_balanced/y_balanced
# (see Cell 9) — a cell that did exactly that was removed because it
# silently overwrote this leak-free split with a fully SMOTE-balanced,
# leaked validation set.
import pandas as pd
import numpy as np
from collections import Counter
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split

# 1. Load the real Kaggle training data
file_path = '/content/data/kaggle/mitbih_train.csv'
df = pd.read_csv(file_path, header=None)

X = df.iloc[:, :187].values
y = df.iloc[:, 187].values.astype(int)

print("Before split — total shape:", X.shape)
print("Class counts:", Counter(y))

# 2. Split FIRST — stratify to preserve class ratios in both splits.
# val stays 100% real, untouched data — this is what makes Val F1 trustworthy.
X_train_raw, X_val, y_train_raw, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("\nTrain (pre-SMOTE):", X_train_raw.shape, Counter(y_train_raw))
print("Val (real, untouched):", X_val.shape, Counter(y_val))

# 3. SMOTE ONLY the training split
print("\nBalancing training set only... Please wait.")
smote = SMOTE(random_state=42)
X_train, y_train = smote.fit_resample(X_train_raw, y_train_raw)

print("\nAfter SMOTE — training set:")
print("Balanced shape:", X_train.shape)
print("Balanced class counts:", Counter(y_train))
print("\nX_val/y_val were NEVER touched by SMOTE — safe for evaluation.")



beat_mask = np.array([s in AAMI for s in raw_symbols])

# =============================================================================
# STEP 1 (v2) — Extraction + preprocessing (run once, reused for both models)
# FIXES vs previous version:
#   (a) RR intervals now computed ONLY from real beat annotations (previously
#       included non-beat annotations, which collapsed some windows to a
#       handful of samples -> near-empty beats dominated by zero-padding)
#   (b) Signal is normalized to [0,1] GLOBALLY per record BEFORE windowing,
#       not per-beat after padding -> zero-padding now sits near the low end
#       of the range like it does in the real Kaggle data, instead of
#       sometimes landing at the top and creating a flat high plateau
# =============================================================================
import numpy as np, torch, json, os
from scipy.signal import butter, filtfilt, resample
from sklearn.metrics import (accuracy_score, f1_score, precision_score,
                             recall_score, classification_report,
                             confusion_matrix, precision_recall_fscore_support)
import wfdb

LOWCUT, HIGHCUT, ORDER = 0.5, 45.0, 4
TARGET_FS               = 125     # match Kaggle mitbih_train.csv sampling rate
TARGET_LEN              = 187     # match Kaggle beat length
WINDOW_RR_FACTOR        = 1.2     # match Kachuee et al. window-length convention
SEED                    = 42
EXPECTED_FS             = 257
NORMALISATION           = 'global_per_record_minmax_0_1_rpeak_anchored_125hz'
CLASSES = ['Normal (N)', 'Supra (S)', 'PVC (V)', 'Fusion (F)', 'Unknown (Q)']
AAMI = {
    'N':0, 'L':0, 'R':0, 'e':0, 'j':0,
    'A':1, 'a':1, 'J':1, 'S':1,
    'V':2, 'E':2,
    'F':3,
    '/':4, 'f':4, 'Q':4,
}
MITBIH_REF = {
    "MultiScaleECGCNN": {'accuracy':0.9818, 'macro_f1':0.8922},
    "ECGResNetSE":       {'accuracy':0.9870, 'macro_f1':0.9251},
}
records = sorted({f.split('.')[0] for f in os.listdir(INCART_DIR) if f.endswith('.hea')})
print('>>> RUNNING STEP1 VERSION: median-rr-v4 <<<')  # <-- confirm this line appears
print(f'\n[2/5] extracting and preprocessing beats from {len(records)} records...')

def bandpass(sig, fs):
    nyq = 0.5 * fs
    b, a = butter(ORDER, [LOWCUT/nyq, min(HIGHCUT/nyq, 0.99)], btype='band')
    return filtfilt(b, a, sig)

X, y, n_skipped_flat, n_skipped_edge = [], [], 0, 0
n_lead_ii, n_lead_fallback = 0, 0
fs_mismatches = []
extra_symbol_counter = [0]
extra_symbol_types = set()
for k, rec in enumerate(records):
    try:
        r   = wfdb.rdrecord(os.path.join(INCART_DIR, rec))
        ann = wfdb.rdann(os.path.join(INCART_DIR, rec), 'atr')
        fs  = int(r.fs)
        if fs != EXPECTED_FS:
            fs_mismatches.append((rec, fs))
        sig_names = [s.strip() for s in r.sig_name]
        if 'II' in sig_names:
            lead_idx = sig_names.index('II')
            n_lead_ii += 1
        else:
            lead_idx = 0
            n_lead_fallback += 1
            print(f'      [lead] {rec}: no lead II found (leads={sig_names}), falling back to channel 0')
        sig = r.p_signal[:, lead_idx].astype(np.float64)
        sig = bandpass(sig, fs)

        # --- resample the WHOLE signal to 125 Hz first, like Kaggle prep ---
        n_samples_125 = int(round(len(sig) * TARGET_FS / fs))
        sig_125 = resample(sig, n_samples_125)

        # --- (b) normalize the WHOLE record to [0,1] BEFORE windowing ---
        sig_min, sig_max = sig_125.min(), sig_125.max()
        sig_range = sig_max - sig_min
        if sig_range < 1e-8:
            continue  # entire record flat, skip
        sig_125_norm = (sig_125 - sig_min) / sig_range

        # --- (a) window length now uses the RECORD'S MEDIAN RR interval,
        # not the local (beat-to-beat) RR. Local RR is noisy: a Normal beat
        # immediately following a PVC's compensatory pause gets an
        # artificially long local RR, inflating its window until it swallows
        # part of the NEXT beat's QRS. A per-record median is stable against
        # that and matches how a fixed representative window size would
        # actually behave.
        ALL_BEAT_SYMBOLS = set(AAMI.keys()) | {'P', '?', 'B', 'r', 'n'}
        raw_samples = np.asarray(ann.sample)
        raw_symbols = np.asarray(ann.symbol)

        all_beat_mask = np.array([s in ALL_BEAT_SYMBOLS for s in raw_symbols])
        all_beat_samples_125 = np.round(raw_samples[all_beat_mask] * TARGET_FS / fs).astype(int)
        all_beat_symbols = raw_symbols[all_beat_mask]

        # diagnostic: are there any beat symbols beyond AAMI's own keys?
        extra_symbols_here = set(all_beat_symbols) - set(AAMI.keys())
        if extra_symbols_here:
            extra_symbol_counter[0] += int(np.sum(~np.isin(all_beat_symbols, list(AAMI.keys()))))
            extra_symbol_types.update(extra_symbols_here)

        full_rr = np.diff(all_beat_samples_125)
        # robust median RR for this record (ignore implausible outliers from
        # noise/missed beats before taking the median)
        plausible_rr = full_rr[(full_rr > 0.3*TARGET_FS) & (full_rr < 2.5*TARGET_FS)]
        record_rr = int(np.median(plausible_rr)) if len(plausible_rr) else TARGET_LEN

        aami_mask = np.array([s in AAMI for s in all_beat_symbols])
        beat_positions = np.where(aami_mask)[0]

        for pos in beat_positions:
            samp125 = all_beat_samples_125[pos]
            sym = all_beat_symbols[pos]
            rr = record_rr

            win_len = max(int(round(WINDOW_RR_FACTOR * rr)), 1)
            lo = samp125
            hi = samp125 + win_len
            if lo < 0 or lo >= len(sig_125_norm):
                n_skipped_edge += 1
                continue

            beat_raw = sig_125_norm[lo:min(hi, len(sig_125_norm))]
            if len(beat_raw) == 0:
                n_skipped_edge += 1
                continue

            # zero-pad to TARGET_LEN (pad value is now meaningful: it's the
            # record's global minimum, not an arbitrary per-beat artifact)
            beat = np.zeros(TARGET_LEN, dtype=np.float64)
            n_copy = min(len(beat_raw), TARGET_LEN)
            beat[:n_copy] = beat_raw[:n_copy]

            if beat.max() - beat.min() < 1e-8:
                n_skipped_flat += 1
                continue
            X.append(beat.astype(np.float32))
            y.append(AAMI[sym])
    except Exception as e:
        print(f'      [skip] {rec}: {e}')
    if (k+1) % 15 == 0:
        print(f'      {k+1}/{len(records)} records | {len(X):,} beats')
X_incart = np.asarray(X, dtype=np.float32)
y_incart = np.asarray(y, dtype=np.int64)
print(f'\n      DONE: {len(X_incart):,} beats')
print(f'      skipped: {n_skipped_flat} flat segments, {n_skipped_edge} boundary-clipped')
print(f'      leads: {n_lead_ii} records used lead II by name, {n_lead_fallback} fell back to channel 0')
if fs_mismatches:
    print(f'      [WARNING] {len(fs_mismatches)} record(s) had fs != {EXPECTED_FS}: {fs_mismatches}')
print(f'      class counts: {dict(zip(*np.unique(y_incart, return_counts=True)))}')
print(f'      [diagnostic] non-AAMI beat annotations found: {extra_symbol_counter[0]}  types: {extra_symbol_types}')

# =============================================================================
# STEP 2b — Diagnostic: does the R-peak actually land at index 0?
# By construction, beat[0] should BE the R-peak sample. This checks whether
# the visual "shift" we're seeing is real or just a rendering illusion, and
# whether windows are overshooting into the next beat's QRS.
# =============================================================================
import numpy as np

# Where is the max-amplitude sample within each beat? (argmax as a proxy for
# "where does the most R-peak-like deflection sit")
argmax_positions = np.argmax(X_incart, axis=1)  # index of peak value per beat

print("Distribution of argmax position across all INCART beats:")
print(f"  min={argmax_positions.min()}  median={np.median(argmax_positions):.1f}  "
      f"mean={argmax_positions.mean():.1f}  max={argmax_positions.max()}")
print(f"  % of beats with argmax at index 0 (i.e. R-peak truly at window start): "
      f"{(argmax_positions == 0).mean()*100:.1f}%")
print(f"  % of beats with argmax within first 5 samples: "
      f"{(argmax_positions <= 5).mean()*100:.1f}%")
print(f"  % of beats with argmax beyond sample 100 (likely catching next beat's QRS): "
      f"{(argmax_positions > 100).mean()*100:.1f}%")

# breakdown by class
print("\nPer-class median argmax position (want this close to 0):")
for cls in range(5):
    idx = np.where(y_incart == cls)[0]
    if len(idx):
        print(f"  class {cls}: median={np.median(argmax_positions[idx]):.1f}  "
              f"n={len(idx)}")

# print raw values for a few individual beats so we can see beat[0] directly
print("\nFirst 10 sample values of 5 random beats (beat[0] should be near the")
print("global max if R-peak truly starts the window):")
rng = np.random.default_rng(1)
sample_idx = rng.choice(len(X_incart), 5, replace=False)
for i in sample_idx:
    b = X_incart[i]
    print(f"  beat {i} (class {y_incart[i]}): beat[0]={b[0]:.3f}  "
          f"argmax={np.argmax(b)}  max_val={b.max():.3f}  beat[:10]={np.round(b[:10],2)}")

# =============================================================================
# STEP 2 — Visual re-check (confirm INCART beats now match MIT-BIH format
# before trusting any inference/metrics below)
# =============================================================================
import matplotlib.pyplot as plt

CLASS_NAMES = {0: 'N', 1: 'S', 2: 'V', 3: 'F', 4: 'Q'}
fig, axes = plt.subplots(2, 5, figsize=(18, 6), facecolor="#0d1117")
rng_plot = np.random.default_rng(0)

for cls in range(5):
    ax_top, ax_bot = axes[0, cls], axes[1, cls]
    for ax in (ax_top, ax_bot):
        ax.set_facecolor("#161b22"); ax.set_xticks([]); ax.set_yticks([])

    idx_i = np.where(y_incart == cls)[0]
    if len(idx_i):
        ax_top.plot(X_incart[rng_plot.choice(idx_i)], color="#58a6ff")
    ax_top.set_title(f"INCART {CLASS_NAMES[cls]} (fixed)", color="#c9d1d9", fontsize=9)

    idx_v = np.where(y_val == cls)[0]
    if len(idx_v):
        ax_bot.plot(X_val[rng_plot.choice(idx_v)], color="#2ea44f")
    ax_bot.set_title(f"MIT-BIH val {CLASS_NAMES[cls]}", color="#c9d1d9", fontsize=9)

plt.tight_layout()
plt.savefig("/content/incart_recheck_v3_fixed.png", dpi=150, facecolor="#0d1117")
plt.show()
print("[OK] visual re-check saved — confirm INCART panels now show the same")
print("     left-edge R-peak spike + flat zero-padded tail as MIT-BIH panels")
print("     before trusting inference/metrics below")

import hashlib
print("X_incart shape:", X_incart.shape)
print("X_incart checksum:", hashlib.md5(X_incart.tobytes()).hexdigest())

# =============================================================================
# CHECKPOINT LOADING — HARDENED (fixes silent-wrong-checkpoint risk)
# =============================================================================
# Change from your version: PASS 2's fallback search matched ANY file
# containing 'multiscale', 'model', 'checkpoint', or 'ecg' — which could
# silently load a different-but-structurally-compatible checkpoint (e.g. the
# non-retrained multiscale_best.pt) that still prints 131,573 params, giving
# a false sense of safety. This version only ever accepts the exact filename
# multiscale_best_retrain.pt, anywhere it's found — never a substitute.
# =============================================================================
import os
import torch
import torch.nn as nn

class DropPath(nn.Module):
    def __init__(self, drop_prob=0.15):
        super().__init__()
        self.drop_prob = drop_prob
    def forward(self, x):
        if not self.training or self.drop_prob == 0.0:
            return x
        keep = 1.0 - self.drop_prob
        shape = (x.shape[0],) + (1,) * (x.ndim - 1)
        mask = torch.rand(shape, device=x.device) < keep
        return x * mask.float() / keep

class SEBlock1D(nn.Module):
    def __init__(self, channels, reduction=8):
        super().__init__()
        self.pool = nn.AdaptiveAvgPool1d(1)
        self.fc = nn.Sequential(
            nn.Linear(channels, max(channels // reduction, 4), bias=False),
            nn.ReLU(inplace=False),
            nn.Linear(max(channels // reduction, 4), channels, bias=False),
            nn.Sigmoid()
        )
    def forward(self, x):
        b, c, _ = x.shape
        y = self.pool(x).view(b, c)
        return x * self.fc(y).view(b, c, 1)

class MultiScaleECGCNN_v2(nn.Module):
    def __init__(self, num_classes=5, input_len=187, dropout=0.5, drop_path=0.15):
        super().__init__()
        ch = 48
        def _path(k):
            pad = k // 2
            return nn.Sequential(
                nn.Conv1d(1, ch, kernel_size=k, padding=pad, bias=False),
                nn.BatchNorm1d(ch), nn.ReLU(inplace=False), nn.Dropout(dropout * 0.5),
                nn.Conv1d(ch, ch, kernel_size=k, padding=pad, bias=False),
                nn.BatchNorm1d(ch), nn.ReLU(inplace=False), nn.AdaptiveAvgPool1d(32)
            )
        self.path_small  = _path(3)
        self.path_medium = _path(9)
        self.path_large  = _path(21)
        self.dp_small  = DropPath(drop_path)
        self.dp_medium = DropPath(drop_path)
        self.dp_large  = DropPath(drop_path)
        merged_ch = ch * 3
        self.se = SEBlock1D(merged_ch)
        self.fusion = nn.Sequential(
            nn.Dropout(dropout * 0.6),
            nn.Conv1d(merged_ch, 96, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm1d(96), nn.ReLU(inplace=False), nn.AdaptiveAvgPool1d(1)
        )
        self.classifier = nn.Sequential(
            nn.Dropout(dropout), nn.Linear(96, 64), nn.ReLU(inplace=False),
            nn.Dropout(dropout * 0.5), nn.Linear(64, num_classes)
        )
    def forward(self, x):
        if x.dim() == 2: x = x.unsqueeze(1)
        p1 = self.dp_small(self.path_small(x))
        p2 = self.dp_medium(self.path_medium(x))
        p3 = self.dp_large(self.path_large(x))
        fused = self.se(torch.cat([p1, p2, p3], dim=1))
        out = self.fusion(fused).squeeze(-1)
        return self.classifier(out)

print('[OK] MultiScaleECGCNN_v2 architecture defined')

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'[OK] Device: {device}\n')

# ── HARDENED SEARCH: exact filename only, no substring fallback ────────────
REQUIRED_NAME = 'multiscale_best_retrain.pt'
SEARCH_DIRS = [
    '/content',
    '/content/drive/MyDrive/ECG_Project_Checkpoints',
    '/content/drive/MyDrive',
    '.',
    './checkpoints',
    './models',
    '/root',
]

print('='*70)
print(f'CHECKPOINT SEARCH — exact filename only: {REQUIRED_NAME}')
print('='*70)

found_path = None
for d in SEARCH_DIRS:
    candidate = os.path.join(d, REQUIRED_NAME)
    if os.path.exists(candidate):
        size_mb = os.path.getsize(candidate) / (1024**2)
        print(f'✓ FOUND: {candidate}  ({size_mb:.2f} MB)')
        found_path = candidate
        break
    print(f'✗ Not found: {candidate}')

if found_path is None:
    raise FileNotFoundError(
        f'\n[FATAL] {REQUIRED_NAME} not found in any of {SEARCH_DIRS}.\n'
        'Unlike the previous version of this cell, this one will NOT fall back '
        'to a differently-named checkpoint (e.g. multiscale_best.pt) — a '
        'structurally-compatible but WRONG checkpoint would silently pass the '
        'param-count check downstream and corrupt your Table 8 numbers without '
        'any error. Locate the real file and either place it at /content/ or '
        'add its exact directory to SEARCH_DIRS above.'
    )

# Known-good size check (534 KB observed for the correct file in your notebook)
size_kb = os.path.getsize(found_path) / 1024
if not (450 <= size_kb <= 650):
    print(f'[WARNING] File size {size_kb:.0f} KB is outside the expected ~500-550 KB '
          f'range for this checkpoint. Double-check this is really the right file '
          f'before trusting results computed from it.')

print(f'\n[OK] Loading: {found_path}')
model = MultiScaleECGCNN_v2(num_classes=5)
state_dict = torch.load(found_path, map_location=device)
model.load_state_dict(state_dict, strict=True)
model.to(device)
model.eval()

n_params = sum(p.numel() for p in model.parameters())
print(f'[OK] Model loaded — params={n_params:,}  device={device}  mode=eval()')
assert n_params == 131_573, (
    f'[STOP] Loaded {found_path} but got {n_params:,} params, not 131,573. '
    'The architecture in this cell no longer matches the checkpoint — '
    'do not proceed until this is resolved.'
)
print(f'[OK] Resolved checkpoint path: {found_path}')
print('[SUCCESS] Model ready for XAI analysis (LIME, GradCAM, SHAP) — '
      'run XAI cells immediately, do not run any other model-defining cell first.')

model_ms= model



import torch, torch.nn as nn, torch.nn.functional as F, os

# --- Architecture (must match training-time definition exactly) ---
class SqueezeExcitation1D(nn.Module):
    def __init__(self, channels, reduction=16):
        super().__init__()
        self.fc = nn.Sequential(
            nn.Linear(channels, channels // reduction, bias=False), nn.ReLU(True),
            nn.Linear(channels // reduction, channels, bias=False), nn.Sigmoid())
    def forward(self, x):
        b, c, _ = x.size(); y = x.mean(dim=2)
        return x * self.fc(y).view(b, c, 1).expand_as(x)

class ResNetBlock1D(nn.Module):
    def __init__(self, in_ch, out_ch, stride=1):
        super().__init__()
        self.conv1 = nn.Conv1d(in_ch, out_ch, 3, stride=stride, padding=1, bias=False)
        self.bn1   = nn.BatchNorm1d(out_ch)
        self.conv2 = nn.Conv1d(out_ch, out_ch, 3, padding=1, bias=False)
        self.bn2   = nn.BatchNorm1d(out_ch)
        self.se    = SqueezeExcitation1D(out_ch)
        self.skip  = nn.Sequential(nn.Conv1d(in_ch, out_ch, 1, stride=stride, bias=False),
                                    nn.BatchNorm1d(out_ch)) if in_ch != out_ch or stride != 1 else nn.Identity()
    def forward(self, x):
        return F.relu(self.se(F.relu(self.bn2(self.conv2(F.relu(self.bn1(self.conv1(x))))))) + self.skip(x))

class ECGResNetSE(nn.Module):
    def __init__(self, num_classes=5):
        super().__init__()
        self.stem   = nn.Sequential(nn.Conv1d(1, 64, 7, padding=3, bias=False), nn.BatchNorm1d(64))
        self.layer1 = ResNetBlock1D(64, 128, stride=2)
        self.layer2 = ResNetBlock1D(128, 256, stride=2)
        self.pool   = nn.AdaptiveAvgPool1d(1)
        self.fc     = nn.Linear(256, num_classes)
    def forward(self, x):
        if x.dim() == 2: x = x.unsqueeze(1)
        return self.fc(self.pool(self.layer2(self.layer1(F.relu(self.stem(x))))).squeeze(-1))

# --- Load checkpoint ---
CHECKPOINT_DIR = "/content/drive/MyDrive/ECG_Project_Checkpoints"
device = "cuda" if torch.cuda.is_available() else "cpu"

model_rn = ECGResNetSE(num_classes=5).to(device)
model_rn.load_state_dict(
    torch.load(os.path.join(CHECKPOINT_DIR, "ecgresnetse_best.pt"), map_location=device)
)
model_rn.eval()
print("[OK] ECGResNetSE loaded from ecgresnetse_best.pt")

import torch, os

# these three class defs must be available (copy them in if this is a fresh session)
# class SqueezeExcitation1D(nn.Module): ...
# class ResNetBlock1D(nn.Module): ...
# class ECGResNetSE(nn.Module): ...

CHECKPOINT_DIR = "/content/drive/MyDrive/ECG_Project_Checkpoints"
device = "cuda" if torch.cuda.is_available() else "cpu"

model_rn = ECGResNetSE(num_classes=5).to(device)
model_rn.load_state_dict(
    torch.load(os.path.join(CHECKPOINT_DIR, "ecgresnetse_best.pt"), map_location=device)
)
model_rn.eval()

import torch, os

# these three class defs must be available (copy them in if this is a fresh session)
# class SqueezeExcitation1D(nn.Module): ...
# class ResNetBlock1D(nn.Module): ...
# class ECGResNetSE(nn.Module): ...

CHECKPOINT_DIR = "/content/drive/MyDrive/ECG_Project_Checkpoints"
device = "cuda" if torch.cuda.is_available() else "cpu"

model_rn = ECGResNetSE(num_classes=5).to(device)
model_rn.load_state_dict(
    torch.load(os.path.join(CHECKPOINT_DIR, "ecgresnetse_best.pt"), map_location=device)
)
model_rn.eval()

# =============================================================================
# STEP 3 — Inference + metrics (both models, on the fixed INCART extraction)
# =============================================================================
import os

def run_validation(model, model_name, device):
    print(f'\n[3/5] running {model_name} (zero-shot)...')
    model.eval()
    preds = []
    with torch.no_grad():
        for i in range(0, len(X_incart), 1024):
            xb = torch.tensor(X_incart[i:i+1024]).unsqueeze(1).to(device)
            preds.append(model(xb).argmax(1).cpu().numpy())
    y_pred = np.concatenate(preds)

    print('[4/5] computing metrics with bootstrap CIs...')
    rng = np.random.default_rng(SEED)
    n = len(y_incart)
    boot = {k: [] for k in ['acc', 'mf1', 'mp', 'mr']}
    for _ in range(1000):
        idx = rng.integers(0, n, n)
        yt, yp = y_incart[idx], y_pred[idx]
        boot['acc'].append(accuracy_score(yt, yp))
        boot['mf1'].append(f1_score(yt, yp, average='macro', zero_division=0))
        boot['mp'].append(precision_score(yt, yp, average='macro', zero_division=0))
        boot['mr'].append(recall_score(yt, yp, average='macro', zero_division=0))
    def ci(v): return float(np.percentile(v, 2.5)), float(np.percentile(v, 97.5))

    acc = accuracy_score(y_incart, y_pred)
    mf1 = f1_score(y_incart, y_pred, average='macro', zero_division=0)
    wf1 = f1_score(y_incart, y_pred, average='weighted', zero_division=0)
    p, r, f, sup = precision_recall_fscore_support(y_incart, y_pred, labels=range(5), zero_division=0)

    print('\n' + '='*74)
    print(f'  EXTERNAL VALIDATION — {model_name} — INCART (zero-shot, FIXED extraction)')
    print('='*74)
    print(f'  beats = {n:,}   records = {len(records)}')
    print(f'  lead selection: {n_lead_ii} by-name (II), {n_lead_fallback} fallback (ch. 0)')
    ref = MITBIH_REF[model_name]
    print(f'\n  {"Metric":18}{"INCART":>10}{"MIT-BIH":>10}{"drop":>9}')
    for name, val in [('accuracy', acc), ('macro_f1', mf1)]:
        print(f'  {name:18}{val:>10.4f}{ref[name]:>10.4f}{val-ref[name]:>+9.4f}')

    print('\n  PER-CLASS')
    for i, c in enumerate(CLASSES):
        print(f'  {c:16} n={sup[i]:>7,}  P={p[i]:.4f}  R={r[i]:.4f}  F1={f[i]:.4f}')

    cm = confusion_matrix(y_incart, y_pred, labels=range(5))
    print('\n  CONFUSION MATRIX (rows=true, cols=pred)')
    print('           ' + ''.join(f'{c.split()[0][:7]:>9}' for c in CLASSES))
    for i, c in enumerate(CLASSES):
        print(f'  {c.split()[0][:8]:9}' + ''.join(f'{v:>9,}' for v in cm[i]))

    print('\n' + classification_report(y_incart, y_pred, target_names=CLASSES, zero_division=0, digits=4))

    os.makedirs('./ecg_results_figures', exist_ok=True)
    res = {'model': model_name, 'dataset': 'INCART', 'n_beats': int(n),
           'normalisation': NORMALISATION,
           'lead_selection': {'by_name_II': n_lead_ii, 'fallback_channel_0': n_lead_fallback},
           'overall': {'accuracy': {'estimate': float(acc), 'ci': ci(boot['acc'])},
                       'macro_f1': {'estimate': float(mf1), 'ci': ci(boot['mf1'])},
                       'weighted_f1': {'estimate': float(wf1)}},
           'confusion_matrix': cm.tolist()}
    with open(f'./ecg_results_figures/external_validation_incart_{model_name}_fixed.json', 'w') as fh:
        json.dump(res, fh, indent=2)
    print(f'[5/5] [SAVED] external_validation_incart_{model_name}_fixed.json')
    return res

results_ms = run_validation(model_ms, "MultiScaleECGCNN", device)
results_rn = run_validation(model_rn, "ECGResNetSE", device)