# -*- coding: utf-8 -*-
"""XAI FAITHFULNESS AND SENSITIVITY METRICS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f-_I4PmUvt4THk-Lgi9_UuNTaPWZmgUX
"""



"""
XAI FAITHFULNESS AND SENSITIVITY METRICS
=========================================
Closes reviewer item #9 (strengthen XAI validation).

WHY THIS IS NEEDED
  The QRS-trust score answers "do the explanations point at clinically sensible
  regions?" It does NOT answer "do the explanations reflect what the model
  actually uses?" A method could score high on QRS-trust while being unfaithful
  (e.g. always highlighting the R-peak regardless of the model). These metrics
  test faithfulness directly, by perturbing the input and observing whether the
  prediction moves the way the attribution predicts it should.

METRICS COMPUTED
  Comprehensiveness  mask the top-k% most-attributed timesteps -> confidence
                     should DROP sharply if the attribution is faithful.  HIGHER = better
  Sufficiency        keep ONLY the top-k% -> confidence should be RETAINED.
                     LOWER = better (small drop when keeping only key regions)
  AOPC-deletion      area over the deletion curve, averaged across k. HIGHER = better
  Sensitivity        add small Gaussian noise, recompute attribution, measure
                     Spearman rho between original and perturbed. HIGHER = more stable
  RANDOM BASELINE    the same metrics using random attributions. This is the
                     control: a faithful method must beat it clearly.

REQUIREMENTS IN MEMORY: model, device
Falls back to loading mitbih_test.csv if X/y are absent.
RUNTIME ~3-6 min for N_SAMPLES=300 on a T4.
"""

import os, json, warnings, numpy as np, torch, torch.nn as nn
from scipy.stats import spearmanr, ConstantInputWarning
warnings.filterwarnings('ignore', category=ConstantInputWarning)

N_SAMPLES = 300          # beats to evaluate
K_FRACS   = [0.05, 0.10, 0.15, 0.20, 0.30, 0.40, 0.50]
NOISE_SD  = 0.01         # for the sensitivity test
N_NOISE   = 5            # perturbation repeats per beat
SEED      = 42
rng = np.random.default_rng(SEED)
torch.manual_seed(SEED)

# ----------------------------------------------------------------------
# STEP 0 — data
# ----------------------------------------------------------------------
if 'X_test_held' in globals() and 'y_test_held' in globals():
    Xa, ya = np.asarray(X_test_held, np.float32), np.asarray(y_test_held, np.int64)
    print('[OK] using X_test_held / y_test_held')
else:
    import pandas as pd
    print('[INFO] loading mitbih_test.csv')
    df = pd.read_csv('/content/data/kaggle/mitbih_test.csv', header=None)
    Xa = df.iloc[:, :187].values.astype(np.float32)
    ya = df.iloc[:, 187].values.astype(np.int64)

# stratified subsample so rare classes are represented
idx = []
per = max(1, N_SAMPLES // 5)
for c in range(5):
    ci = np.where(ya == c)[0]
    if len(ci):
        idx.extend(rng.choice(ci, min(per, len(ci)), replace=False))
idx = np.array(idx)
X, y = Xa[idx], ya[idx]
print(f'[OK] {len(X)} beats | class counts {dict(zip(*np.unique(y, return_counts=True)))}')

model.eval()

def fwd(batch):
    """probabilities for a numpy batch [N,187]"""
    out = []
    with torch.no_grad():
        for i in range(0, len(batch), 512):
            xb = torch.tensor(batch[i:i+512], dtype=torch.float32).unsqueeze(1).to(device)
            out.append(torch.softmax(model(xb), 1).cpu().numpy())
    return np.concatenate(out)

P0 = fwd(X)
pred = P0.argmax(1)
conf0 = P0[np.arange(len(X)), pred]
print(f'[OK] baseline mean confidence = {conf0.mean():.4f}')

# ----------------------------------------------------------------------
# STEP 1 — attributions
# ----------------------------------------------------------------------
def gradcam_attr(Xb, targets):
    """Grad-CAM on the last Conv1d layer, upsampled to 187."""
    convs = [m for m in model.modules() if isinstance(m, nn.Conv1d)]
    layer = convs[-1]
    acts, grads = {}, {}
    h1 = layer.register_forward_hook(lambda m,i,o: acts.__setitem__('a', o))
    h2 = layer.register_full_backward_hook(lambda m,gi,go: grads.__setitem__('g', go[0]))
    A = np.zeros((len(Xb), 187), np.float32)
    for i in range(0, len(Xb), 128):
        xb = torch.tensor(Xb[i:i+128], dtype=torch.float32).unsqueeze(1).to(device)
        tb = torch.tensor(targets[i:i+128]).to(device)
        model.zero_grad()
        out = model(xb)
        out.gather(1, tb.view(-1,1)).sum().backward()
        a, g = acts['a'], grads['g']
        w   = g.mean(dim=2, keepdim=True)
        cam = torch.relu((w * a).sum(1))                       # [B, L]
        cam = torch.nn.functional.interpolate(
                cam.unsqueeze(1), size=187, mode='linear', align_corners=False).squeeze(1)
        A[i:i+128] = cam.detach().cpu().numpy()
    h1.remove(); h2.remove()
    return A

def saliency_attr(Xb, targets):
    """|d logit / d input| — a second, hook-free attribution for comparison."""
    A = np.zeros((len(Xb), 187), np.float32)
    for i in range(0, len(Xb), 128):
        xb = torch.tensor(Xb[i:i+128], dtype=torch.float32).unsqueeze(1).to(device).requires_grad_(True)
        tb = torch.tensor(targets[i:i+128]).to(device)
        model.zero_grad()
        model(xb).gather(1, tb.view(-1,1)).sum().backward()
        A[i:i+128] = xb.grad.abs().squeeze(1).cpu().numpy()
    return A

print('[1/4] computing attributions...')
ATTR = {
    'Grad-CAM': gradcam_attr(X, pred),
    'Saliency': saliency_attr(X, pred),
    'Random':   rng.random((len(X), 187)).astype(np.float32),   # control
}

# ----------------------------------------------------------------------
# STEP 2 — comprehensiveness / sufficiency / AOPC
# ----------------------------------------------------------------------
def mask_topk(Xb, A, frac, keep_only=False):
    """Replace top-k% attributed timesteps with the beat mean (or keep only those)."""
    k = max(1, int(frac * 187))
    out = Xb.copy()
    order = np.argsort(-A, axis=1)[:, :k]
    base = Xb.mean(axis=1, keepdims=True)
    if keep_only:
        out = np.repeat(base, 187, axis=1).astype(np.float32)
        for r in range(len(Xb)):
            out[r, order[r]] = Xb[r, order[r]]
    else:
        for r in range(len(Xb)):
            out[r, order[r]] = base[r, 0]
    return out

print('[2/4] deletion / insertion curves...')
results = {}
for name, A in ATTR.items():
    comp, suff = [], []
    for fr in K_FRACS:
        Pd = fwd(mask_topk(X, A, fr, keep_only=False))
        Pi = fwd(mask_topk(X, A, fr, keep_only=True))
        comp.append(float((conf0 - Pd[np.arange(len(X)), pred]).mean()))
        suff.append(float((conf0 - Pi[np.arange(len(X)), pred]).mean()))
    results[name] = {'comprehensiveness': comp, 'sufficiency': suff,
                     'aopc_deletion': float(np.mean(comp))}

# ----------------------------------------------------------------------
# STEP 3 — sensitivity / stability
# ----------------------------------------------------------------------
print('[3/4] sensitivity under input perturbation...')
for name in ['Grad-CAM', 'Saliency']:
    rhos = []
    base_A = ATTR[name]
    for _ in range(N_NOISE):
        Xn = (X + rng.normal(0, NOISE_SD, X.shape)).astype(np.float32)
        An = gradcam_attr(Xn, pred) if name == 'Grad-CAM' else saliency_attr(Xn, pred)
        for r in range(len(X)):
            rho, _ = spearmanr(base_A[r], An[r])
            if not np.isnan(rho): rhos.append(rho)
    results[name]['sensitivity_spearman'] = float(np.mean(rhos))
    results[name]['sensitivity_sd']       = float(np.std(rhos))
results['Random']['sensitivity_spearman'] = 0.0
results['Random']['sensitivity_sd']       = 0.0

# ----------------------------------------------------------------------
# STEP 4 — report
# ----------------------------------------------------------------------
print('\n' + '=' * 78)
print(f'  XAI FAITHFULNESS AND SENSITIVITY   (n = {len(X)} beats, seed {SEED})')
print('=' * 78)
print(f'  {"Method":12}{"AOPC-del":>11}{"Comp@10%":>11}{"Comp@20%":>11}{"Suff@20%":>11}{"Stability":>11}')
print('  ' + '-' * 68)
i10, i20 = K_FRACS.index(0.10), K_FRACS.index(0.20)
for name in ['Grad-CAM', 'Saliency', 'Random']:
    r = results[name]
    print(f'  {name:12}{r["aopc_deletion"]:>11.4f}'
          f'{r["comprehensiveness"][i10]:>11.4f}{r["comprehensiveness"][i20]:>11.4f}'
          f'{r["sufficiency"][i20]:>11.4f}{r["sensitivity_spearman"]:>11.4f}')

print('\n  READING THE TABLE')
print('  ' + '-' * 68)
print('  AOPC-del / Comp : HIGHER is better (masking important points hurts the model)')
print('  Suff            : LOWER  is better (keeping only important points preserves it)')
print('  Stability       : HIGHER is better (explanation robust to small input noise)')
gc, rd = results['Grad-CAM']['aopc_deletion'], results['Random']['aopc_deletion']
if rd > 1e-6:
    print(f'\n  Grad-CAM AOPC is {gc/rd:.2f}x the random baseline ({gc:.4f} vs {rd:.4f})')
else:
    print(f'\n  Grad-CAM AOPC {gc:.4f} vs random {rd:.4f}  (absolute margin {gc-rd:+.4f})')
if gc <= rd:
    print('  [WARNING] attribution does NOT beat the random control -- report this honestly;')
    print('            it would indicate the explanations are not faithful to the model.')
else:
    print('  A faithful attribution must clearly exceed the random control, which it does.')

print('\n  DELETION CURVE (confidence drop vs fraction masked)')
print('  ' + '-' * 68)
print('  ' + 'frac'.ljust(8) + ''.join(f'{f:>9.0%}' for f in K_FRACS))
for name in ['Grad-CAM', 'Saliency', 'Random']:
    print(f'  {name:8}' + ''.join(f'{v:>9.4f}' for v in results[name]['comprehensiveness']))

os.makedirs('./ecg_results_figures', exist_ok=True)
json.dump({'n_beats': int(len(X)), 'seed': SEED, 'k_fracs': K_FRACS,
           'noise_sd': NOISE_SD, 'results': results},
          open('./ecg_results_figures/xai_faithfulness.json', 'w'), indent=2)
print('\n[SAVED] ./ecg_results_figures/xai_faithfulness.json')
print('[DONE]  Paste the table above back to have it written into the manuscript.')



import matplotlib.pyplot as plt
import numpy as np

k_fracs = [0.05, 0.10, 0.15, 0.20, 0.30, 0.40, 0.50]

data = {
    'Grad-CAM': [0.1553, 0.4348, 0.5908, 0.6389, 0.6823, 0.7465, 0.7400],
    'Saliency': [0.2664, 0.4479, 0.5423, 0.6055, 0.6619, 0.7144, 0.7225],
    'Random':   [0.1137, 0.2062, 0.2825, 0.3433, 0.4756, 0.5560, 0.6284],
}

colors = {'Grad-CAM': '#1b5fb4', 'Saliency': '#d9822b', 'Random': '#9a9a9a'}
markers = {'Grad-CAM': 'o', 'Saliency': 's', 'Random': '^'}
linestyles = {'Grad-CAM': '-', 'Saliency': '-', 'Random': '--'}

fig, ax = plt.subplots(figsize=(7, 5), dpi=200)

for name, vals in data.items():
    ax.plot(np.array(k_fracs) * 100, vals,
            label=name, color=colors[name], marker=markers[name],
            linestyle=linestyles[name], linewidth=2.2, markersize=7,
            zorder=3 if name != 'Random' else 2)

ax.set_xlabel('Fraction of timesteps masked (%)', fontsize=12)
ax.set_ylabel('Mean confidence drop\n(comprehensiveness)', fontsize=12)
ax.set_title('Deletion Curve: Faithfulness of Attribution Methods\n(n = 300 beats, MIT-BIH)', fontsize=12.5, pad=12)

ax.set_ylim(0, 0.85)
ax.set_xlim(0, 52)
ax.grid(True, alpha=0.3, linestyle=':')
ax.legend(loc='lower right', fontsize=11, frameon=True, framealpha=0.9)

# annotate the AOPC summary
ax.text(0.02, 0.97,
        'AOPC-deletion:\nGrad-CAM: 0.570 (1.53× random)\nSaliency:  0.566 (1.52× random)\nRandom:    0.372',
        transform=ax.transAxes, fontsize=9.5, va='top', ha='left',
        bbox=dict(boxstyle='round,pad=0.4', facecolor='white', edgecolor='#cccccc'))

for spine in ['top', 'right']:
    ax.spines[spine].set_visible(False)

plt.tight_layout()
plt.savefig('/content/ecg_results_figures/deletion_curve.png', bbox_inches='tight')
plt.savefig('/content/ecg_results_figures/deletion_curve.pdf', bbox_inches='tight')
print('saved')